// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.13.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import 'frb_generated.dart';

import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

/// Solved aigis header value (session-bound, single-use).
class AigisTokenDto {
  final String token;

  const AigisTokenDto({required this.token});

  @override
  int get hashCode => token.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is AigisTokenDto &&
          runtimeType == other.runtimeType &&
          token == other.token;
}

/// Outcome of a QR approval.
class ApprovalOutcome {
  final List<StepReport> steps;

  /// Game reported by the scan response (e.g. 原神). Empty when unknown.
  final String appName;

  /// Masked account name from the scan response.
  final String accountDispName;

  /// Risk note from the scan response, when the server sent one.
  final String riskNote;
  final bool scanned;
  final bool approved;

  /// 来源描述：屏幕捕获/截图文件/二维码链接/直播·<标签或房间号>。
  final String source;

  /// 仅扫描时暂存：手动批准所需的 passport 票据（一次性，短期有效）。
  final String? pendingTicket;

  /// 仅扫描时暂存：批准所需的 token_types。
  final List<String> pendingTokenTypes;

  const ApprovalOutcome({
    required this.steps,
    required this.appName,
    required this.accountDispName,
    required this.riskNote,
    required this.scanned,
    required this.approved,
    required this.source,
    this.pendingTicket,
    required this.pendingTokenTypes,
  });

  @override
  int get hashCode =>
      steps.hashCode ^
      appName.hashCode ^
      accountDispName.hashCode ^
      riskNote.hashCode ^
      scanned.hashCode ^
      approved.hashCode ^
      source.hashCode ^
      pendingTicket.hashCode ^
      pendingTokenTypes.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ApprovalOutcome &&
          runtimeType == other.runtimeType &&
          steps == other.steps &&
          appName == other.appName &&
          accountDispName == other.accountDispName &&
          riskNote == other.riskNote &&
          scanned == other.scanned &&
          approved == other.approved &&
          source == other.source &&
          pendingTicket == other.pendingTicket &&
          pendingTokenTypes == other.pendingTokenTypes;
}

/// One line of the audit log.
class AuditEntryDto {
  /// Unix seconds.
  final String at;
  final String account;

  /// `qr_login_game` | `qr_scan` | `qr_cancel`
  final String action;
  final bool ok;

  /// Non-secret summary. Never a token, ticket, or code.
  final String detail;

  /// Server retcode when the action failed on the server side.
  final PlatformInt64? retcode;

  const AuditEntryDto({
    required this.at,
    required this.account,
    required this.action,
    required this.ok,
    required this.detail,
    this.retcode,
  });

  @override
  int get hashCode =>
      at.hashCode ^
      account.hashCode ^
      action.hashCode ^
      ok.hashCode ^
      detail.hashCode ^
      retcode.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is AuditEntryDto &&
          runtimeType == other.runtimeType &&
          at == other.at &&
          account == other.account &&
          action == other.action &&
          ok == other.ok &&
          detail == other.detail &&
          retcode == other.retcode;
}

/// Static description of the core, shown on a settings/about screen.
class BridgeInfo {
  final String coreVersion;
  final String dataDir;
  final String passportHost;
  final String deviceApiHost;

  /// Supported `game_biz` values.
  final List<String> games;

  /// Accepted `--template` names.
  final List<String> deviceTemplates;

  const BridgeInfo({
    required this.coreVersion,
    required this.dataDir,
    required this.passportHost,
    required this.deviceApiHost,
    required this.games,
    required this.deviceTemplates,
  });

  @override
  int get hashCode =>
      coreVersion.hashCode ^
      dataDir.hashCode ^
      passportHost.hashCode ^
      deviceApiHost.hashCode ^
      games.hashCode ^
      deviceTemplates.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is BridgeInfo &&
          runtimeType == other.runtimeType &&
          coreVersion == other.coreVersion &&
          dataDir == other.dataDir &&
          passportHost == other.passportHost &&
          deviceApiHost == other.deviceApiHost &&
          games == other.games &&
          deviceTemplates == other.deviceTemplates;
}

/// Masked view of a stored virtual device.
class DeviceSummary {
  final String account;
  final String model;
  final String brand;
  final String androidVersion;
  final String sdkVersion;
  final String gameBiz;
  final String deviceIdMasked;
  final BigInt deviceIdLen;
  final String deviceFpMasked;
  final BigInt deviceFpLen;

  /// True when a server registration exists for this profile.
  final bool registered;

  const DeviceSummary({
    required this.account,
    required this.model,
    required this.brand,
    required this.androidVersion,
    required this.sdkVersion,
    required this.gameBiz,
    required this.deviceIdMasked,
    required this.deviceIdLen,
    required this.deviceFpMasked,
    required this.deviceFpLen,
    required this.registered,
  });

  @override
  int get hashCode =>
      account.hashCode ^
      model.hashCode ^
      brand.hashCode ^
      androidVersion.hashCode ^
      sdkVersion.hashCode ^
      gameBiz.hashCode ^
      deviceIdMasked.hashCode ^
      deviceIdLen.hashCode ^
      deviceFpMasked.hashCode ^
      deviceFpLen.hashCode ^
      registered.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is DeviceSummary &&
          runtimeType == other.runtimeType &&
          account == other.account &&
          model == other.model &&
          brand == other.brand &&
          androidVersion == other.androidVersion &&
          sdkVersion == other.sdkVersion &&
          gameBiz == other.gameBiz &&
          deviceIdMasked == other.deviceIdMasked &&
          deviceIdLen == other.deviceIdLen &&
          deviceFpMasked == other.deviceFpMasked &&
          deviceFpLen == other.deviceFpLen &&
          registered == other.registered;
}

/// A persisted on/off flag (developer mode).
class FlagDto {
  final bool enabled;

  /// Unix seconds of the last change; empty when never set.
  final String updatedAt;

  const FlagDto({required this.enabled, required this.updatedAt});

  @override
  int get hashCode => enabled.hashCode ^ updatedAt.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is FlagDto &&
          runtimeType == other.runtimeType &&
          enabled == other.enabled &&
          updatedAt == other.updatedAt;
}

/// A manual challenge the UI must surface to the user.
class LoginChallengeDto {
  /// `sms_captcha` | `interactive_risk` | `real_name` | `unknown`
  final String kind;
  final PlatformInt64 retcode;
  final String message;
  final List<String> hints;

  /// kind == "aigis"：应用内求解页地址（本地服务器，等待人工完成）。
  final String? aigisUrl;

  /// kind == "aigis"：求解会话句柄，完成后传给 aigis_take。
  final BigInt? aigisHandle;

  /// Ready-to-display manual instructions. Never an automated bypass.
  final String instructions;

  const LoginChallengeDto({
    required this.kind,
    required this.retcode,
    required this.message,
    required this.hints,
    this.aigisUrl,
    this.aigisHandle,
    required this.instructions,
  });

  @override
  int get hashCode =>
      kind.hashCode ^
      retcode.hashCode ^
      message.hashCode ^
      hints.hashCode ^
      aigisUrl.hashCode ^
      aigisHandle.hashCode ^
      instructions.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is LoginChallengeDto &&
          runtimeType == other.runtimeType &&
          kind == other.kind &&
          retcode == other.retcode &&
          message == other.message &&
          hints == other.hints &&
          aigisUrl == other.aigisUrl &&
          aigisHandle == other.aigisHandle &&
          instructions == other.instructions;
}

/// Live status of a multi-source race.
class RaceStatusDto {
  final bool running;
  final int watchersTotal;
  final int watchersAlive;
  final bool approved;

  /// First watcher-level failure worth reporting.
  final String? error;

  /// Per-watcher states, in the order the specs were given.
  final List<WatcherStateDto> watchers;

  const RaceStatusDto({
    required this.running,
    required this.watchersTotal,
    required this.watchersAlive,
    required this.approved,
    this.error,
    required this.watchers,
  });

  @override
  int get hashCode =>
      running.hashCode ^
      watchersTotal.hashCode ^
      watchersAlive.hashCode ^
      approved.hashCode ^
      error.hashCode ^
      watchers.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is RaceStatusDto &&
          runtimeType == other.runtimeType &&
          running == other.running &&
          watchersTotal == other.watchersTotal &&
          watchersAlive == other.watchersAlive &&
          approved == other.approved &&
          error == other.error &&
          watchers == other.watchers;
}

/// Result of a `getFp` registration round trip.
class RegistrationSummary {
  final String account;
  final String deviceIdMasked;
  final String deviceFpMasked;
  final BigInt deviceFpLen;

  const RegistrationSummary({
    required this.account,
    required this.deviceIdMasked,
    required this.deviceFpMasked,
    required this.deviceFpLen,
  });

  @override
  int get hashCode =>
      account.hashCode ^
      deviceIdMasked.hashCode ^
      deviceFpMasked.hashCode ^
      deviceFpLen.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is RegistrationSummary &&
          runtimeType == other.runtimeType &&
          account == other.account &&
          deviceIdMasked == other.deviceIdMasked &&
          deviceFpMasked == other.deviceFpMasked &&
          deviceFpLen == other.deviceFpLen;
}

/// 进行中的单路捕获进度：让界面能显示「在扫、扫到什么」，
/// 而不是一个静默的转圈。只含计数与状态，不含任何画面或令牌。
class ScanProgressDto {
  /// 已抓取的帧数。
  final BigInt frames;

  /// 解出过二维码的帧数（同一张码反复解出会累计）。
  final BigInt decoded;

  /// 已解出但还在等待稳定（需连续/近似连续的重复）。
  final bool waitingStable;

  /// 最近一次失败（抓屏失败或解码失败）的原因。
  final String lastError;

  const ScanProgressDto({
    required this.frames,
    required this.decoded,
    required this.waitingStable,
    required this.lastError,
  });

  @override
  int get hashCode =>
      frames.hashCode ^
      decoded.hashCode ^
      waitingStable.hashCode ^
      lastError.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ScanProgressDto &&
          runtimeType == other.runtimeType &&
          frames == other.frames &&
          decoded == other.decoded &&
          waitingStable == other.waitingStable &&
          lastError == other.lastError;
}

/// Result of probing a stored session against the server.
class SessionProbeDto {
  /// true = the stored stoken still works.
  final bool valid;

  /// Human-readable outcome (no tokens).
  final String message;

  /// Masked account id from the probe response, when valid.
  final String uidMasked;

  const SessionProbeDto({
    required this.valid,
    required this.message,
    required this.uidMasked,
  });

  @override
  int get hashCode => valid.hashCode ^ message.hashCode ^ uidMasked.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is SessionProbeDto &&
          runtimeType == other.runtimeType &&
          valid == other.valid &&
          message == other.message &&
          uidMasked == other.uidMasked;
}

/// Masked view of a stored session.
class SessionSummary {
  final String account;
  final BigInt accountUidLen;
  final BigInt stokenLen;

  /// `v2_` for current tokens; empty when unknown.
  final String stokenPrefix;
  final String midMasked;

  /// Mid that goes into the QR Cookie (per account).
  final String qrMidMasked;
  final BigInt cookieTokenLen;
  final BigInt ltokenLen;
  final String updatedAt;

  /// Progress steps of the operation that produced this summary.
  final List<StepReport> steps;

  const SessionSummary({
    required this.account,
    required this.accountUidLen,
    required this.stokenLen,
    required this.stokenPrefix,
    required this.midMasked,
    required this.qrMidMasked,
    required this.cookieTokenLen,
    required this.ltokenLen,
    required this.updatedAt,
    required this.steps,
  });

  @override
  int get hashCode =>
      account.hashCode ^
      accountUidLen.hashCode ^
      stokenLen.hashCode ^
      stokenPrefix.hashCode ^
      midMasked.hashCode ^
      qrMidMasked.hashCode ^
      cookieTokenLen.hashCode ^
      ltokenLen.hashCode ^
      updatedAt.hashCode ^
      steps.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is SessionSummary &&
          runtimeType == other.runtimeType &&
          account == other.account &&
          accountUidLen == other.accountUidLen &&
          stokenLen == other.stokenLen &&
          stokenPrefix == other.stokenPrefix &&
          midMasked == other.midMasked &&
          qrMidMasked == other.qrMidMasked &&
          cookieTokenLen == other.cookieTokenLen &&
          ltokenLen == other.ltokenLen &&
          updatedAt == other.updatedAt &&
          steps == other.steps;
}

/// What the server said when an SMS code was requested.
///
/// The UI needs `countdown` to offer a resend; without it the request button
/// latches after the first send and a failed login has no way back.
class SmsRequestDto {
  /// False when the server reused a code it had already sent.
  final bool sentNew;

  /// Seconds before another request is allowed; 0 when the server did not say.
  final BigInt countdown;

  /// `action_type` the server expects on the submit call; usually
  /// `login_by_mobile_captcha`.
  final String actionType;

  const SmsRequestDto({
    required this.sentNew,
    required this.countdown,
    required this.actionType,
  });

  @override
  int get hashCode =>
      sentNew.hashCode ^ countdown.hashCode ^ actionType.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is SmsRequestDto &&
          runtimeType == other.runtimeType &&
          sentNew == other.sentNew &&
          countdown == other.countdown &&
          actionType == other.actionType;
}

/// One step of a multi-step operation, for progress display.
class StepReport {
  /// 1-based step number.
  final int index;
  final int total;
  final String name;
  final String detail;
  final bool ok;

  const StepReport({
    required this.index,
    required this.total,
    required this.name,
    required this.detail,
    required this.ok,
  });

  @override
  int get hashCode =>
      index.hashCode ^
      total.hashCode ^
      name.hashCode ^
      detail.hashCode ^
      ok.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is StepReport &&
          runtimeType == other.runtimeType &&
          index == other.index &&
          total == other.total &&
          name == other.name &&
          detail == other.detail &&
          ok == other.ok;
}

/// A persisted string setting (e.g. last logged-in account label).
class TextDto {
  final String value;

  const TextDto({required this.value});

  @override
  int get hashCode => value.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is TextDto &&
          runtimeType == other.runtimeType &&
          value == other.value;
}

/// One race source spec.
class WatcherSpecDto {
  /// "bilibili" | "screen"。
  final String kind;
  final String? room;
  final String label;

  /// "approve" | "scan"。
  final String mode;

  const WatcherSpecDto({
    required this.kind,
    this.room,
    required this.label,
    required this.mode,
  });

  @override
  int get hashCode =>
      kind.hashCode ^ room.hashCode ^ label.hashCode ^ mode.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is WatcherSpecDto &&
          runtimeType == other.runtimeType &&
          kind == other.kind &&
          room == other.room &&
          label == other.label &&
          mode == other.mode;
}

/// One watched source (Bilibili room or the local screen) in a race.
class WatcherStateDto {
  /// 稳定键：label 或房间号。
  final String key;

  /// "bilibili" | "screen"。
  final String kind;
  final String? room;
  final String label;

  /// "approve"（自动批准）| "scan"（仅扫描，等待手动批准）。
  final String mode;
  final bool alive;

  /// 该源的稳定二维码抢到了胜者名额。
  final bool winner;
  final bool scanned;
  final bool approved;
  final String? qrUrl;

  /// mode == "scan" 时暂存的票据，等待手动批准（qr_confirm_pending）。
  final String? pendingTicket;
  final List<String> pendingTokenTypes;
  final String? error;

  /// 胜者扫描到的游戏显示名（供结果卡与弹窗展示；未扫描时为空）。
  final String appName;

  /// 扫码账号的显示名（掩码）。
  final String accountDispName;

  /// 服务端风控备注（通常为空）。
  final String riskNote;

  /// 已解码帧数（直播源 = ffmpeg 输出帧；屏幕源 = 截屏次数）。
  final BigInt frames;

  /// 解出过二维码的帧数。
  final BigInt decodedFrames;

  /// 最近一帧的解码说明，如「本帧未解出二维码」。
  final String hint;

  /// 最近一帧的分辨率（如 1280x720）。
  final String resolution;

  /// 实测帧率（帧/s，滚动窗口均值）。
  final double fps;

  /// 与流服务器的 TCP 连接时延（≈ping，毫秒）；屏幕源为 None。
  final BigInt? pingMs;

  const WatcherStateDto({
    required this.key,
    required this.kind,
    this.room,
    required this.label,
    required this.mode,
    required this.alive,
    required this.winner,
    required this.scanned,
    required this.approved,
    this.qrUrl,
    this.pendingTicket,
    required this.pendingTokenTypes,
    this.error,
    required this.appName,
    required this.accountDispName,
    required this.riskNote,
    required this.frames,
    required this.decodedFrames,
    required this.hint,
    required this.resolution,
    required this.fps,
    this.pingMs,
  });

  @override
  int get hashCode =>
      key.hashCode ^
      kind.hashCode ^
      room.hashCode ^
      label.hashCode ^
      mode.hashCode ^
      alive.hashCode ^
      winner.hashCode ^
      scanned.hashCode ^
      approved.hashCode ^
      qrUrl.hashCode ^
      pendingTicket.hashCode ^
      pendingTokenTypes.hashCode ^
      error.hashCode ^
      appName.hashCode ^
      accountDispName.hashCode ^
      riskNote.hashCode ^
      frames.hashCode ^
      decodedFrames.hashCode ^
      hint.hashCode ^
      resolution.hashCode ^
      fps.hashCode ^
      pingMs.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is WatcherStateDto &&
          runtimeType == other.runtimeType &&
          key == other.key &&
          kind == other.kind &&
          room == other.room &&
          label == other.label &&
          mode == other.mode &&
          alive == other.alive &&
          winner == other.winner &&
          scanned == other.scanned &&
          approved == other.approved &&
          qrUrl == other.qrUrl &&
          pendingTicket == other.pendingTicket &&
          pendingTokenTypes == other.pendingTokenTypes &&
          error == other.error &&
          appName == other.appName &&
          accountDispName == other.accountDispName &&
          riskNote == other.riskNote &&
          frames == other.frames &&
          decodedFrames == other.decodedFrames &&
          hint == other.hint &&
          resolution == other.resolution &&
          fps == other.fps &&
          pingMs == other.pingMs;
}
