// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.13.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import 'dto.dart';
import 'frb_generated.dart';

import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';
import 'package:freezed_annotation/freezed_annotation.dart' hide protected;
part 'error.freezed.dart';

@freezed
sealed class BridgeError with _$BridgeError implements FrbException {
  const BridgeError._();

  const factory BridgeError.invalid(String field0) = BridgeError_Invalid;
  const factory BridgeError.accountNotFound(String field0) =
      BridgeError_AccountNotFound;
  const factory BridgeError.api({
    required PlatformInt64 retcode,
    required String message,
  }) = BridgeError_Api;

  /// The user must complete a challenge manually. Never an automated bypass.
  const factory BridgeError.challenge(LoginChallengeDto field0) =
      BridgeError_Challenge;
  const factory BridgeError.storage(String field0) = BridgeError_Storage;
  const factory BridgeError.capture(String field0) = BridgeError_Capture;
  const factory BridgeError.qr(String field0) = BridgeError_Qr;
}
