// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.13.0.

// ignore_for_file: unused_import, unused_element, unnecessary_import, duplicate_ignore, invalid_use_of_internal_member, annotate_overrides, non_constant_identifier_names, curly_braces_in_flow_control_structures, prefer_const_literals_to_create_immutables, unused_field

import 'api/auth.dart';
import 'api/core.dart';
import 'api/device.dart';
import 'api/qr.dart';
import 'api/race.dart';
import 'api/settings.dart';

import 'dart:async';
import 'dart:convert';

import 'dto.dart';
import 'error.dart';
import 'frb_generated.dart';
import 'frb_generated.io.dart'
    if (dart.library.js_interop) 'frb_generated.web.dart';

import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

/// Main entrypoint of the Rust API
class RustLib extends BaseEntrypoint<RustLibApi, RustLibApiImpl, RustLibWire> {
  @internal
  static final instance = RustLib._();

  RustLib._();

  /// Initialize flutter_rust_bridge
  static Future<void> init({
    RustLibApi? api,
    BaseHandler? handler,
    ExternalLibrary? externalLibrary,
    bool forceSameCodegenVersion = true,
  }) async {
    await instance.initImpl(
      api: api,
      handler: handler,
      externalLibrary: externalLibrary,
      forceSameCodegenVersion: forceSameCodegenVersion,
    );
  }

  /// Initialize flutter_rust_bridge in mock mode.
  /// No libraries for FFI are loaded.
  static void initMock({required RustLibApi api}) {
    instance.initMockImpl(api: api);
  }

  /// Dispose flutter_rust_bridge
  ///
  /// The call to this function is optional, since flutter_rust_bridge (and everything else)
  /// is automatically disposed when the app stops.
  static void dispose() => instance.disposeImpl();

  @override
  ApiImplConstructor<RustLibApiImpl, RustLibWire> get apiImplConstructor =>
      RustLibApiImpl.new;

  @override
  WireConstructor<RustLibWire> get wireConstructor =>
      RustLibWire.fromExternalLibrary;

  @override
  Future<void> executeRustInitializers() async {}

  @override
  ExternalLibraryLoaderConfig get defaultExternalLibraryLoaderConfig =>
      kDefaultExternalLibraryLoaderConfig;

  @override
  String get codegenVersion => '2.13.0';

  @override
  int get rustContentHash => 1695145418;

  static const kDefaultExternalLibraryLoaderConfig =
      ExternalLibraryLoaderConfig(
        stem: 'mhy_qrscanner_bridge',
        ioDirectory: '../crates/mhy-qrscanner-bridge/target/release/',
        webPrefix: 'pkg/',
        wasmBindgenName: 'wasm_bindgen',
      );
}

abstract class RustLibApi extends BaseApi {
  Future<BridgeInfo> crateApiCoreCoreInfo({required Core that});

  Future<void> crateApiAuthAigisCancel({required BigInt handle});

  Future<AigisTokenDto> crateApiAuthAigisTake({
    required BigInt handle,
    required BigInt timeoutSecs,
  });

  Future<void> crateApiRaceAppShutdown();

  Future<List<AuditEntryDto>> crateApiSettingsAuditRecent({
    required Core core,
    required int limit,
  });

  Future<SessionSummary> crateApiAuthAuthLoginPassword({
    required Core core,
    required String account,
    required String login,
    required String password,
    String? aigisToken,
  });

  Future<void> crateApiAuthAuthLogout({
    required Core core,
    required String account,
  });

  Future<SmsRequestDto> crateApiAuthAuthRequestSms({
    required Core core,
    required String account,
    required String login,
    required String areaCode,
    String? aigisToken,
  });

  Future<SessionSummary> crateApiAuthAuthShow({
    required Core core,
    required String account,
  });

  Future<SessionSummary> crateApiAuthAuthSubmitSms({
    required Core core,
    required String account,
    required String login,
    required String areaCode,
    required String code,
  });

  Future<Core> crateApiCoreCoreNew();

  Future<Core> crateApiCoreCoreNewAt({required String dataDir});

  Future<String> crateApiCoreDefaultDataDir();

  Future<DeviceSummary> crateApiDeviceDeviceCreate({
    required Core core,
    required String account,
    required String template,
    required bool force,
  });

  Future<void> crateApiDeviceDeviceDelete({
    required Core core,
    required String account,
  });

  Future<List<DeviceSummary>> crateApiDeviceDeviceList({required Core core});

  Future<RegistrationSummary> crateApiDeviceDeviceRegister({
    required Core core,
    required String account,
  });

  Future<DeviceSummary> crateApiDeviceDeviceSetGameBiz({
    required Core core,
    required String account,
    required String gameBiz,
  });

  Future<DeviceSummary> crateApiDeviceDeviceShow({
    required Core core,
    required String account,
  });

  Future<FlagDto> crateApiSettingsFlagGet({
    required Core core,
    required String key,
  });

  Future<FlagDto> crateApiSettingsFlagSet({
    required Core core,
    required String key,
    required bool enabled,
  });

  Future<void> crateApiQrQrCancel({
    required Core core,
    required String account,
    required String urlOrTicket,
    required List<String> tokenTypes,
  });

  Future<ApprovalOutcome> crateApiQrQrConfirmPending({
    required Core core,
    required String account,
    required String ticket,
    required List<String> tokenTypes,
  });

  Future<ApprovalOutcome> crateApiQrQrLoginGame({
    required Core core,
    required String account,
    required QrSource source,
    required bool confirm,
  });

  Future<int> crateApiRaceQrRaceStart({
    required Core core,
    required String account,
    required List<WatcherSpecDto> specs,
    BigInt? waitSecs,
  });

  Future<RaceStatusDto> crateApiRaceQrRaceStatus({required int id});

  Future<void> crateApiRaceQrRaceStop({required int id});

  Future<ApprovalOutcome> crateApiQrQrScan({
    required Core core,
    required String account,
    required String passportQrUrl,
    required bool confirm,
  });

  Future<ScanProgressDto> crateApiQrQrScanProgress();

  Future<void> crateApiQrScanStop();

  Future<SessionProbeDto> crateApiAuthSessionProbe({
    required Core core,
    required String account,
  });

  Future<TextDto> crateApiSettingsTextGet({
    required Core core,
    required String key,
  });

  Future<TextDto> crateApiSettingsTextSet({
    required Core core,
    required String key,
    required String value,
  });

  RustArcIncrementStrongCountFnType get rust_arc_increment_strong_count_Core;

  RustArcDecrementStrongCountFnType get rust_arc_decrement_strong_count_Core;

  CrossPlatformFinalizerArg get rust_arc_decrement_strong_count_CorePtr;
}

class RustLibApiImpl extends RustLibApiImplPlatform implements RustLibApi {
  RustLibApiImpl({
    required super.handler,
    required super.wire,
    required super.generalizedFrbRustBinding,
    required super.portManager,
  });

  @override
  Future<BridgeInfo> crateApiCoreCoreInfo({required Core that}) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerCore(
            that,
            serializer,
          );
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 1,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_bridge_info,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiCoreCoreInfoConstMeta,
        argValues: [that],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiCoreCoreInfoConstMeta =>
      const TaskConstMeta(debugName: "Core_info", argNames: ["that"]);

  @override
  Future<void> crateApiAuthAigisCancel({required BigInt handle}) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_u_64(handle, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 2,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiAuthAigisCancelConstMeta,
        argValues: [handle],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiAuthAigisCancelConstMeta =>
      const TaskConstMeta(debugName: "aigis_cancel", argNames: ["handle"]);

  @override
  Future<AigisTokenDto> crateApiAuthAigisTake({
    required BigInt handle,
    required BigInt timeoutSecs,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_u_64(handle, serializer);
          sse_encode_u_64(timeoutSecs, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 3,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_aigis_token_dto,
          decodeErrorData: sse_decode_bridge_error,
        ),
        constMeta: kCrateApiAuthAigisTakeConstMeta,
        argValues: [handle, timeoutSecs],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiAuthAigisTakeConstMeta => const TaskConstMeta(
    debugName: "aigis_take",
    argNames: ["handle", "timeoutSecs"],
  );

  @override
  Future<void> crateApiRaceAppShutdown() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 4,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiRaceAppShutdownConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiRaceAppShutdownConstMeta =>
      const TaskConstMeta(debugName: "app_shutdown", argNames: []);

  @override
  Future<List<AuditEntryDto>> crateApiSettingsAuditRecent({
    required Core core,
    required int limit,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerCore(
            core,
            serializer,
          );
          sse_encode_u_32(limit, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 5,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_list_audit_entry_dto,
          decodeErrorData: sse_decode_bridge_error,
        ),
        constMeta: kCrateApiSettingsAuditRecentConstMeta,
        argValues: [core, limit],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiSettingsAuditRecentConstMeta =>
      const TaskConstMeta(
        debugName: "audit_recent",
        argNames: ["core", "limit"],
      );

  @override
  Future<SessionSummary> crateApiAuthAuthLoginPassword({
    required Core core,
    required String account,
    required String login,
    required String password,
    String? aigisToken,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerCore(
            core,
            serializer,
          );
          sse_encode_String(account, serializer);
          sse_encode_String(login, serializer);
          sse_encode_String(password, serializer);
          sse_encode_opt_String(aigisToken, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 6,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_session_summary,
          decodeErrorData: sse_decode_bridge_error,
        ),
        constMeta: kCrateApiAuthAuthLoginPasswordConstMeta,
        argValues: [core, account, login, password, aigisToken],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiAuthAuthLoginPasswordConstMeta =>
      const TaskConstMeta(
        debugName: "auth_login_password",
        argNames: ["core", "account", "login", "password", "aigisToken"],
      );

  @override
  Future<void> crateApiAuthAuthLogout({
    required Core core,
    required String account,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerCore(
            core,
            serializer,
          );
          sse_encode_String(account, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 7,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_bridge_error,
        ),
        constMeta: kCrateApiAuthAuthLogoutConstMeta,
        argValues: [core, account],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiAuthAuthLogoutConstMeta => const TaskConstMeta(
    debugName: "auth_logout",
    argNames: ["core", "account"],
  );

  @override
  Future<SmsRequestDto> crateApiAuthAuthRequestSms({
    required Core core,
    required String account,
    required String login,
    required String areaCode,
    String? aigisToken,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerCore(
            core,
            serializer,
          );
          sse_encode_String(account, serializer);
          sse_encode_String(login, serializer);
          sse_encode_String(areaCode, serializer);
          sse_encode_opt_String(aigisToken, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 8,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_sms_request_dto,
          decodeErrorData: sse_decode_bridge_error,
        ),
        constMeta: kCrateApiAuthAuthRequestSmsConstMeta,
        argValues: [core, account, login, areaCode, aigisToken],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiAuthAuthRequestSmsConstMeta => const TaskConstMeta(
    debugName: "auth_request_sms",
    argNames: ["core", "account", "login", "areaCode", "aigisToken"],
  );

  @override
  Future<SessionSummary> crateApiAuthAuthShow({
    required Core core,
    required String account,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerCore(
            core,
            serializer,
          );
          sse_encode_String(account, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 9,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_session_summary,
          decodeErrorData: sse_decode_bridge_error,
        ),
        constMeta: kCrateApiAuthAuthShowConstMeta,
        argValues: [core, account],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiAuthAuthShowConstMeta => const TaskConstMeta(
    debugName: "auth_show",
    argNames: ["core", "account"],
  );

  @override
  Future<SessionSummary> crateApiAuthAuthSubmitSms({
    required Core core,
    required String account,
    required String login,
    required String areaCode,
    required String code,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerCore(
            core,
            serializer,
          );
          sse_encode_String(account, serializer);
          sse_encode_String(login, serializer);
          sse_encode_String(areaCode, serializer);
          sse_encode_String(code, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 10,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_session_summary,
          decodeErrorData: sse_decode_bridge_error,
        ),
        constMeta: kCrateApiAuthAuthSubmitSmsConstMeta,
        argValues: [core, account, login, areaCode, code],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiAuthAuthSubmitSmsConstMeta => const TaskConstMeta(
    debugName: "auth_submit_sms",
    argNames: ["core", "account", "login", "areaCode", "code"],
  );

  @override
  Future<Core> crateApiCoreCoreNew() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 11,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData:
              sse_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerCore,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiCoreCoreNewConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiCoreCoreNewConstMeta =>
      const TaskConstMeta(debugName: "core_new", argNames: []);

  @override
  Future<Core> crateApiCoreCoreNewAt({required String dataDir}) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(dataDir, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 12,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData:
              sse_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerCore,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiCoreCoreNewAtConstMeta,
        argValues: [dataDir],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiCoreCoreNewAtConstMeta =>
      const TaskConstMeta(debugName: "core_new_at", argNames: ["dataDir"]);

  @override
  Future<String> crateApiCoreDefaultDataDir() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 13,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiCoreDefaultDataDirConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiCoreDefaultDataDirConstMeta =>
      const TaskConstMeta(debugName: "default_data_dir", argNames: []);

  @override
  Future<DeviceSummary> crateApiDeviceDeviceCreate({
    required Core core,
    required String account,
    required String template,
    required bool force,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerCore(
            core,
            serializer,
          );
          sse_encode_String(account, serializer);
          sse_encode_String(template, serializer);
          sse_encode_bool(force, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 14,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_device_summary,
          decodeErrorData: sse_decode_bridge_error,
        ),
        constMeta: kCrateApiDeviceDeviceCreateConstMeta,
        argValues: [core, account, template, force],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiDeviceDeviceCreateConstMeta => const TaskConstMeta(
    debugName: "device_create",
    argNames: ["core", "account", "template", "force"],
  );

  @override
  Future<void> crateApiDeviceDeviceDelete({
    required Core core,
    required String account,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerCore(
            core,
            serializer,
          );
          sse_encode_String(account, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 15,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_bridge_error,
        ),
        constMeta: kCrateApiDeviceDeviceDeleteConstMeta,
        argValues: [core, account],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiDeviceDeviceDeleteConstMeta => const TaskConstMeta(
    debugName: "device_delete",
    argNames: ["core", "account"],
  );

  @override
  Future<List<DeviceSummary>> crateApiDeviceDeviceList({required Core core}) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerCore(
            core,
            serializer,
          );
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 16,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_list_device_summary,
          decodeErrorData: sse_decode_bridge_error,
        ),
        constMeta: kCrateApiDeviceDeviceListConstMeta,
        argValues: [core],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiDeviceDeviceListConstMeta =>
      const TaskConstMeta(debugName: "device_list", argNames: ["core"]);

  @override
  Future<RegistrationSummary> crateApiDeviceDeviceRegister({
    required Core core,
    required String account,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerCore(
            core,
            serializer,
          );
          sse_encode_String(account, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 17,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_registration_summary,
          decodeErrorData: sse_decode_bridge_error,
        ),
        constMeta: kCrateApiDeviceDeviceRegisterConstMeta,
        argValues: [core, account],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiDeviceDeviceRegisterConstMeta =>
      const TaskConstMeta(
        debugName: "device_register",
        argNames: ["core", "account"],
      );

  @override
  Future<DeviceSummary> crateApiDeviceDeviceSetGameBiz({
    required Core core,
    required String account,
    required String gameBiz,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerCore(
            core,
            serializer,
          );
          sse_encode_String(account, serializer);
          sse_encode_String(gameBiz, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 18,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_device_summary,
          decodeErrorData: sse_decode_bridge_error,
        ),
        constMeta: kCrateApiDeviceDeviceSetGameBizConstMeta,
        argValues: [core, account, gameBiz],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiDeviceDeviceSetGameBizConstMeta =>
      const TaskConstMeta(
        debugName: "device_set_game_biz",
        argNames: ["core", "account", "gameBiz"],
      );

  @override
  Future<DeviceSummary> crateApiDeviceDeviceShow({
    required Core core,
    required String account,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerCore(
            core,
            serializer,
          );
          sse_encode_String(account, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 19,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_device_summary,
          decodeErrorData: sse_decode_bridge_error,
        ),
        constMeta: kCrateApiDeviceDeviceShowConstMeta,
        argValues: [core, account],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiDeviceDeviceShowConstMeta => const TaskConstMeta(
    debugName: "device_show",
    argNames: ["core", "account"],
  );

  @override
  Future<FlagDto> crateApiSettingsFlagGet({
    required Core core,
    required String key,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerCore(
            core,
            serializer,
          );
          sse_encode_String(key, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 20,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_flag_dto,
          decodeErrorData: sse_decode_bridge_error,
        ),
        constMeta: kCrateApiSettingsFlagGetConstMeta,
        argValues: [core, key],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiSettingsFlagGetConstMeta =>
      const TaskConstMeta(debugName: "flag_get", argNames: ["core", "key"]);

  @override
  Future<FlagDto> crateApiSettingsFlagSet({
    required Core core,
    required String key,
    required bool enabled,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerCore(
            core,
            serializer,
          );
          sse_encode_String(key, serializer);
          sse_encode_bool(enabled, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 21,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_flag_dto,
          decodeErrorData: sse_decode_bridge_error,
        ),
        constMeta: kCrateApiSettingsFlagSetConstMeta,
        argValues: [core, key, enabled],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiSettingsFlagSetConstMeta => const TaskConstMeta(
    debugName: "flag_set",
    argNames: ["core", "key", "enabled"],
  );

  @override
  Future<void> crateApiQrQrCancel({
    required Core core,
    required String account,
    required String urlOrTicket,
    required List<String> tokenTypes,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerCore(
            core,
            serializer,
          );
          sse_encode_String(account, serializer);
          sse_encode_String(urlOrTicket, serializer);
          sse_encode_list_String(tokenTypes, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 22,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_bridge_error,
        ),
        constMeta: kCrateApiQrQrCancelConstMeta,
        argValues: [core, account, urlOrTicket, tokenTypes],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiQrQrCancelConstMeta => const TaskConstMeta(
    debugName: "qr_cancel",
    argNames: ["core", "account", "urlOrTicket", "tokenTypes"],
  );

  @override
  Future<ApprovalOutcome> crateApiQrQrConfirmPending({
    required Core core,
    required String account,
    required String ticket,
    required List<String> tokenTypes,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerCore(
            core,
            serializer,
          );
          sse_encode_String(account, serializer);
          sse_encode_String(ticket, serializer);
          sse_encode_list_String(tokenTypes, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 23,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_approval_outcome,
          decodeErrorData: sse_decode_bridge_error,
        ),
        constMeta: kCrateApiQrQrConfirmPendingConstMeta,
        argValues: [core, account, ticket, tokenTypes],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiQrQrConfirmPendingConstMeta => const TaskConstMeta(
    debugName: "qr_confirm_pending",
    argNames: ["core", "account", "ticket", "tokenTypes"],
  );

  @override
  Future<ApprovalOutcome> crateApiQrQrLoginGame({
    required Core core,
    required String account,
    required QrSource source,
    required bool confirm,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerCore(
            core,
            serializer,
          );
          sse_encode_String(account, serializer);
          sse_encode_box_autoadd_qr_source(source, serializer);
          sse_encode_bool(confirm, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 24,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_approval_outcome,
          decodeErrorData: sse_decode_bridge_error,
        ),
        constMeta: kCrateApiQrQrLoginGameConstMeta,
        argValues: [core, account, source, confirm],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiQrQrLoginGameConstMeta => const TaskConstMeta(
    debugName: "qr_login_game",
    argNames: ["core", "account", "source", "confirm"],
  );

  @override
  Future<int> crateApiRaceQrRaceStart({
    required Core core,
    required String account,
    required List<WatcherSpecDto> specs,
    BigInt? waitSecs,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerCore(
            core,
            serializer,
          );
          sse_encode_String(account, serializer);
          sse_encode_list_watcher_spec_dto(specs, serializer);
          sse_encode_opt_box_autoadd_u_64(waitSecs, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 25,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_u_32,
          decodeErrorData: sse_decode_bridge_error,
        ),
        constMeta: kCrateApiRaceQrRaceStartConstMeta,
        argValues: [core, account, specs, waitSecs],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiRaceQrRaceStartConstMeta => const TaskConstMeta(
    debugName: "qr_race_start",
    argNames: ["core", "account", "specs", "waitSecs"],
  );

  @override
  Future<RaceStatusDto> crateApiRaceQrRaceStatus({required int id}) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_u_32(id, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 26,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_race_status_dto,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiRaceQrRaceStatusConstMeta,
        argValues: [id],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiRaceQrRaceStatusConstMeta =>
      const TaskConstMeta(debugName: "qr_race_status", argNames: ["id"]);

  @override
  Future<void> crateApiRaceQrRaceStop({required int id}) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_u_32(id, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 27,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_bridge_error,
        ),
        constMeta: kCrateApiRaceQrRaceStopConstMeta,
        argValues: [id],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiRaceQrRaceStopConstMeta =>
      const TaskConstMeta(debugName: "qr_race_stop", argNames: ["id"]);

  @override
  Future<ApprovalOutcome> crateApiQrQrScan({
    required Core core,
    required String account,
    required String passportQrUrl,
    required bool confirm,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerCore(
            core,
            serializer,
          );
          sse_encode_String(account, serializer);
          sse_encode_String(passportQrUrl, serializer);
          sse_encode_bool(confirm, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 28,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_approval_outcome,
          decodeErrorData: sse_decode_bridge_error,
        ),
        constMeta: kCrateApiQrQrScanConstMeta,
        argValues: [core, account, passportQrUrl, confirm],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiQrQrScanConstMeta => const TaskConstMeta(
    debugName: "qr_scan",
    argNames: ["core", "account", "passportQrUrl", "confirm"],
  );

  @override
  Future<ScanProgressDto> crateApiQrQrScanProgress() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 29,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_scan_progress_dto,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiQrQrScanProgressConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiQrQrScanProgressConstMeta =>
      const TaskConstMeta(debugName: "qr_scan_progress", argNames: []);

  @override
  Future<void> crateApiQrScanStop() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 30,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiQrScanStopConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiQrScanStopConstMeta =>
      const TaskConstMeta(debugName: "scan_stop", argNames: []);

  @override
  Future<SessionProbeDto> crateApiAuthSessionProbe({
    required Core core,
    required String account,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerCore(
            core,
            serializer,
          );
          sse_encode_String(account, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 31,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_session_probe_dto,
          decodeErrorData: sse_decode_bridge_error,
        ),
        constMeta: kCrateApiAuthSessionProbeConstMeta,
        argValues: [core, account],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiAuthSessionProbeConstMeta => const TaskConstMeta(
    debugName: "session_probe",
    argNames: ["core", "account"],
  );

  @override
  Future<TextDto> crateApiSettingsTextGet({
    required Core core,
    required String key,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerCore(
            core,
            serializer,
          );
          sse_encode_String(key, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 32,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_text_dto,
          decodeErrorData: sse_decode_bridge_error,
        ),
        constMeta: kCrateApiSettingsTextGetConstMeta,
        argValues: [core, key],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiSettingsTextGetConstMeta =>
      const TaskConstMeta(debugName: "text_get", argNames: ["core", "key"]);

  @override
  Future<TextDto> crateApiSettingsTextSet({
    required Core core,
    required String key,
    required String value,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerCore(
            core,
            serializer,
          );
          sse_encode_String(key, serializer);
          sse_encode_String(value, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 33,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_text_dto,
          decodeErrorData: sse_decode_bridge_error,
        ),
        constMeta: kCrateApiSettingsTextSetConstMeta,
        argValues: [core, key, value],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiSettingsTextSetConstMeta => const TaskConstMeta(
    debugName: "text_set",
    argNames: ["core", "key", "value"],
  );

  RustArcIncrementStrongCountFnType
  get rust_arc_increment_strong_count_Core => wire
      .rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerCore;

  RustArcDecrementStrongCountFnType
  get rust_arc_decrement_strong_count_Core => wire
      .rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerCore;

  @protected
  Core
  dco_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerCore(
    dynamic raw,
  ) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return CoreImpl.frbInternalDcoDecode(raw as List<dynamic>);
  }

  @protected
  Core
  dco_decode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerCore(
    dynamic raw,
  ) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return CoreImpl.frbInternalDcoDecode(raw as List<dynamic>);
  }

  @protected
  Core
  dco_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerCore(
    dynamic raw,
  ) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return CoreImpl.frbInternalDcoDecode(raw as List<dynamic>);
  }

  @protected
  String dco_decode_String(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as String;
  }

  @protected
  AigisTokenDto dco_decode_aigis_token_dto(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 1)
      throw Exception('unexpected arr length: expect 1 but see ${arr.length}');
    return AigisTokenDto(token: dco_decode_String(arr[0]));
  }

  @protected
  ApprovalOutcome dco_decode_approval_outcome(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 9)
      throw Exception('unexpected arr length: expect 9 but see ${arr.length}');
    return ApprovalOutcome(
      steps: dco_decode_list_step_report(arr[0]),
      appName: dco_decode_String(arr[1]),
      accountDispName: dco_decode_String(arr[2]),
      riskNote: dco_decode_String(arr[3]),
      scanned: dco_decode_bool(arr[4]),
      approved: dco_decode_bool(arr[5]),
      source: dco_decode_String(arr[6]),
      pendingTicket: dco_decode_opt_String(arr[7]),
      pendingTokenTypes: dco_decode_list_String(arr[8]),
    );
  }

  @protected
  AuditEntryDto dco_decode_audit_entry_dto(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 6)
      throw Exception('unexpected arr length: expect 6 but see ${arr.length}');
    return AuditEntryDto(
      at: dco_decode_String(arr[0]),
      account: dco_decode_String(arr[1]),
      action: dco_decode_String(arr[2]),
      ok: dco_decode_bool(arr[3]),
      detail: dco_decode_String(arr[4]),
      retcode: dco_decode_opt_box_autoadd_i_64(arr[5]),
    );
  }

  @protected
  bool dco_decode_bool(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as bool;
  }

  @protected
  PlatformInt64 dco_decode_box_autoadd_i_64(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dco_decode_i_64(raw);
  }

  @protected
  LoginChallengeDto dco_decode_box_autoadd_login_challenge_dto(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dco_decode_login_challenge_dto(raw);
  }

  @protected
  QrSource dco_decode_box_autoadd_qr_source(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dco_decode_qr_source(raw);
  }

  @protected
  BigInt dco_decode_box_autoadd_u_64(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dco_decode_u_64(raw);
  }

  @protected
  BridgeError dco_decode_bridge_error(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    switch (raw[0]) {
      case 0:
        return BridgeError_Invalid(dco_decode_String(raw[1]));
      case 1:
        return BridgeError_AccountNotFound(dco_decode_String(raw[1]));
      case 2:
        return BridgeError_Api(
          retcode: dco_decode_i_64(raw[1]),
          message: dco_decode_String(raw[2]),
        );
      case 3:
        return BridgeError_Challenge(
          dco_decode_box_autoadd_login_challenge_dto(raw[1]),
        );
      case 4:
        return BridgeError_Storage(dco_decode_String(raw[1]));
      case 5:
        return BridgeError_Capture(dco_decode_String(raw[1]));
      case 6:
        return BridgeError_Qr(dco_decode_String(raw[1]));
      default:
        throw Exception("unreachable");
    }
  }

  @protected
  BridgeInfo dco_decode_bridge_info(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 6)
      throw Exception('unexpected arr length: expect 6 but see ${arr.length}');
    return BridgeInfo(
      coreVersion: dco_decode_String(arr[0]),
      dataDir: dco_decode_String(arr[1]),
      passportHost: dco_decode_String(arr[2]),
      deviceApiHost: dco_decode_String(arr[3]),
      games: dco_decode_list_String(arr[4]),
      deviceTemplates: dco_decode_list_String(arr[5]),
    );
  }

  @protected
  DeviceSummary dco_decode_device_summary(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 11)
      throw Exception('unexpected arr length: expect 11 but see ${arr.length}');
    return DeviceSummary(
      account: dco_decode_String(arr[0]),
      model: dco_decode_String(arr[1]),
      brand: dco_decode_String(arr[2]),
      androidVersion: dco_decode_String(arr[3]),
      sdkVersion: dco_decode_String(arr[4]),
      gameBiz: dco_decode_String(arr[5]),
      deviceIdMasked: dco_decode_String(arr[6]),
      deviceIdLen: dco_decode_usize(arr[7]),
      deviceFpMasked: dco_decode_String(arr[8]),
      deviceFpLen: dco_decode_usize(arr[9]),
      registered: dco_decode_bool(arr[10]),
    );
  }

  @protected
  double dco_decode_f_64(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as double;
  }

  @protected
  FlagDto dco_decode_flag_dto(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 2)
      throw Exception('unexpected arr length: expect 2 but see ${arr.length}');
    return FlagDto(
      enabled: dco_decode_bool(arr[0]),
      updatedAt: dco_decode_String(arr[1]),
    );
  }

  @protected
  PlatformInt64 dco_decode_i_64(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dcoDecodeI64(raw);
  }

  @protected
  List<String> dco_decode_list_String(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_String).toList();
  }

  @protected
  List<AuditEntryDto> dco_decode_list_audit_entry_dto(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_audit_entry_dto).toList();
  }

  @protected
  List<DeviceSummary> dco_decode_list_device_summary(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_device_summary).toList();
  }

  @protected
  Uint8List dco_decode_list_prim_u_8_strict(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as Uint8List;
  }

  @protected
  List<StepReport> dco_decode_list_step_report(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_step_report).toList();
  }

  @protected
  List<WatcherSpecDto> dco_decode_list_watcher_spec_dto(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_watcher_spec_dto).toList();
  }

  @protected
  List<WatcherStateDto> dco_decode_list_watcher_state_dto(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_watcher_state_dto).toList();
  }

  @protected
  LoginChallengeDto dco_decode_login_challenge_dto(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 7)
      throw Exception('unexpected arr length: expect 7 but see ${arr.length}');
    return LoginChallengeDto(
      kind: dco_decode_String(arr[0]),
      retcode: dco_decode_i_64(arr[1]),
      message: dco_decode_String(arr[2]),
      hints: dco_decode_list_String(arr[3]),
      aigisUrl: dco_decode_opt_String(arr[4]),
      aigisHandle: dco_decode_opt_box_autoadd_u_64(arr[5]),
      instructions: dco_decode_String(arr[6]),
    );
  }

  @protected
  String? dco_decode_opt_String(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw == null ? null : dco_decode_String(raw);
  }

  @protected
  PlatformInt64? dco_decode_opt_box_autoadd_i_64(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw == null ? null : dco_decode_box_autoadd_i_64(raw);
  }

  @protected
  BigInt? dco_decode_opt_box_autoadd_u_64(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw == null ? null : dco_decode_box_autoadd_u_64(raw);
  }

  @protected
  QrSource dco_decode_qr_source(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    switch (raw[0]) {
      case 0:
        return QrSource_Url(dco_decode_String(raw[1]));
      case 1:
        return QrSource_Image(dco_decode_String(raw[1]));
      case 2:
        return QrSource_Screen(
          waitSecs: dco_decode_opt_box_autoadd_u_64(raw[1]),
        );
      case 3:
        return QrSource_Bilibili(
          roomId: dco_decode_String(raw[1]),
          waitSecs: dco_decode_opt_box_autoadd_u_64(raw[2]),
        );
      default:
        throw Exception("unreachable");
    }
  }

  @protected
  RaceStatusDto dco_decode_race_status_dto(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 6)
      throw Exception('unexpected arr length: expect 6 but see ${arr.length}');
    return RaceStatusDto(
      running: dco_decode_bool(arr[0]),
      watchersTotal: dco_decode_u_32(arr[1]),
      watchersAlive: dco_decode_u_32(arr[2]),
      approved: dco_decode_bool(arr[3]),
      error: dco_decode_opt_String(arr[4]),
      watchers: dco_decode_list_watcher_state_dto(arr[5]),
    );
  }

  @protected
  RegistrationSummary dco_decode_registration_summary(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 4)
      throw Exception('unexpected arr length: expect 4 but see ${arr.length}');
    return RegistrationSummary(
      account: dco_decode_String(arr[0]),
      deviceIdMasked: dco_decode_String(arr[1]),
      deviceFpMasked: dco_decode_String(arr[2]),
      deviceFpLen: dco_decode_usize(arr[3]),
    );
  }

  @protected
  ScanProgressDto dco_decode_scan_progress_dto(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 4)
      throw Exception('unexpected arr length: expect 4 but see ${arr.length}');
    return ScanProgressDto(
      frames: dco_decode_u_64(arr[0]),
      decoded: dco_decode_u_64(arr[1]),
      waitingStable: dco_decode_bool(arr[2]),
      lastError: dco_decode_String(arr[3]),
    );
  }

  @protected
  SessionProbeDto dco_decode_session_probe_dto(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 3)
      throw Exception('unexpected arr length: expect 3 but see ${arr.length}');
    return SessionProbeDto(
      valid: dco_decode_bool(arr[0]),
      message: dco_decode_String(arr[1]),
      uidMasked: dco_decode_String(arr[2]),
    );
  }

  @protected
  SessionSummary dco_decode_session_summary(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 10)
      throw Exception('unexpected arr length: expect 10 but see ${arr.length}');
    return SessionSummary(
      account: dco_decode_String(arr[0]),
      accountUidLen: dco_decode_usize(arr[1]),
      stokenLen: dco_decode_usize(arr[2]),
      stokenPrefix: dco_decode_String(arr[3]),
      midMasked: dco_decode_String(arr[4]),
      qrMidMasked: dco_decode_String(arr[5]),
      cookieTokenLen: dco_decode_usize(arr[6]),
      ltokenLen: dco_decode_usize(arr[7]),
      updatedAt: dco_decode_String(arr[8]),
      steps: dco_decode_list_step_report(arr[9]),
    );
  }

  @protected
  SmsRequestDto dco_decode_sms_request_dto(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 3)
      throw Exception('unexpected arr length: expect 3 but see ${arr.length}');
    return SmsRequestDto(
      sentNew: dco_decode_bool(arr[0]),
      countdown: dco_decode_u_64(arr[1]),
      actionType: dco_decode_String(arr[2]),
    );
  }

  @protected
  StepReport dco_decode_step_report(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 5)
      throw Exception('unexpected arr length: expect 5 but see ${arr.length}');
    return StepReport(
      index: dco_decode_u_32(arr[0]),
      total: dco_decode_u_32(arr[1]),
      name: dco_decode_String(arr[2]),
      detail: dco_decode_String(arr[3]),
      ok: dco_decode_bool(arr[4]),
    );
  }

  @protected
  TextDto dco_decode_text_dto(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 1)
      throw Exception('unexpected arr length: expect 1 but see ${arr.length}');
    return TextDto(value: dco_decode_String(arr[0]));
  }

  @protected
  int dco_decode_u_32(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  BigInt dco_decode_u_64(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dcoDecodeU64(raw);
  }

  @protected
  int dco_decode_u_8(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  void dco_decode_unit(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return;
  }

  @protected
  BigInt dco_decode_usize(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dcoDecodeU64(raw);
  }

  @protected
  WatcherSpecDto dco_decode_watcher_spec_dto(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 4)
      throw Exception('unexpected arr length: expect 4 but see ${arr.length}');
    return WatcherSpecDto(
      kind: dco_decode_String(arr[0]),
      room: dco_decode_opt_String(arr[1]),
      label: dco_decode_String(arr[2]),
      mode: dco_decode_String(arr[3]),
    );
  }

  @protected
  WatcherStateDto dco_decode_watcher_state_dto(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 22)
      throw Exception('unexpected arr length: expect 22 but see ${arr.length}');
    return WatcherStateDto(
      key: dco_decode_String(arr[0]),
      kind: dco_decode_String(arr[1]),
      room: dco_decode_opt_String(arr[2]),
      label: dco_decode_String(arr[3]),
      mode: dco_decode_String(arr[4]),
      alive: dco_decode_bool(arr[5]),
      winner: dco_decode_bool(arr[6]),
      scanned: dco_decode_bool(arr[7]),
      approved: dco_decode_bool(arr[8]),
      qrUrl: dco_decode_opt_String(arr[9]),
      pendingTicket: dco_decode_opt_String(arr[10]),
      pendingTokenTypes: dco_decode_list_String(arr[11]),
      error: dco_decode_opt_String(arr[12]),
      appName: dco_decode_String(arr[13]),
      accountDispName: dco_decode_String(arr[14]),
      riskNote: dco_decode_String(arr[15]),
      frames: dco_decode_u_64(arr[16]),
      decodedFrames: dco_decode_u_64(arr[17]),
      hint: dco_decode_String(arr[18]),
      resolution: dco_decode_String(arr[19]),
      fps: dco_decode_f_64(arr[20]),
      pingMs: dco_decode_opt_box_autoadd_u_64(arr[21]),
    );
  }

  @protected
  Core
  sse_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerCore(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return CoreImpl.frbInternalSseDecode(
      sse_decode_usize(deserializer),
      sse_decode_i_32(deserializer),
    );
  }

  @protected
  Core
  sse_decode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerCore(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return CoreImpl.frbInternalSseDecode(
      sse_decode_usize(deserializer),
      sse_decode_i_32(deserializer),
    );
  }

  @protected
  Core
  sse_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerCore(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return CoreImpl.frbInternalSseDecode(
      sse_decode_usize(deserializer),
      sse_decode_i_32(deserializer),
    );
  }

  @protected
  String sse_decode_String(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_list_prim_u_8_strict(deserializer);
    return utf8.decoder.convert(inner);
  }

  @protected
  AigisTokenDto sse_decode_aigis_token_dto(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_token = sse_decode_String(deserializer);
    return AigisTokenDto(token: var_token);
  }

  @protected
  ApprovalOutcome sse_decode_approval_outcome(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_steps = sse_decode_list_step_report(deserializer);
    var var_appName = sse_decode_String(deserializer);
    var var_accountDispName = sse_decode_String(deserializer);
    var var_riskNote = sse_decode_String(deserializer);
    var var_scanned = sse_decode_bool(deserializer);
    var var_approved = sse_decode_bool(deserializer);
    var var_source = sse_decode_String(deserializer);
    var var_pendingTicket = sse_decode_opt_String(deserializer);
    var var_pendingTokenTypes = sse_decode_list_String(deserializer);
    return ApprovalOutcome(
      steps: var_steps,
      appName: var_appName,
      accountDispName: var_accountDispName,
      riskNote: var_riskNote,
      scanned: var_scanned,
      approved: var_approved,
      source: var_source,
      pendingTicket: var_pendingTicket,
      pendingTokenTypes: var_pendingTokenTypes,
    );
  }

  @protected
  AuditEntryDto sse_decode_audit_entry_dto(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_at = sse_decode_String(deserializer);
    var var_account = sse_decode_String(deserializer);
    var var_action = sse_decode_String(deserializer);
    var var_ok = sse_decode_bool(deserializer);
    var var_detail = sse_decode_String(deserializer);
    var var_retcode = sse_decode_opt_box_autoadd_i_64(deserializer);
    return AuditEntryDto(
      at: var_at,
      account: var_account,
      action: var_action,
      ok: var_ok,
      detail: var_detail,
      retcode: var_retcode,
    );
  }

  @protected
  bool sse_decode_bool(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint8() != 0;
  }

  @protected
  PlatformInt64 sse_decode_box_autoadd_i_64(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_i_64(deserializer));
  }

  @protected
  LoginChallengeDto sse_decode_box_autoadd_login_challenge_dto(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_login_challenge_dto(deserializer));
  }

  @protected
  QrSource sse_decode_box_autoadd_qr_source(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_qr_source(deserializer));
  }

  @protected
  BigInt sse_decode_box_autoadd_u_64(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_u_64(deserializer));
  }

  @protected
  BridgeError sse_decode_bridge_error(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var tag_ = sse_decode_i_32(deserializer);
    switch (tag_) {
      case 0:
        var var_field0 = sse_decode_String(deserializer);
        return BridgeError_Invalid(var_field0);
      case 1:
        var var_field0 = sse_decode_String(deserializer);
        return BridgeError_AccountNotFound(var_field0);
      case 2:
        var var_retcode = sse_decode_i_64(deserializer);
        var var_message = sse_decode_String(deserializer);
        return BridgeError_Api(retcode: var_retcode, message: var_message);
      case 3:
        var var_field0 = sse_decode_box_autoadd_login_challenge_dto(
          deserializer,
        );
        return BridgeError_Challenge(var_field0);
      case 4:
        var var_field0 = sse_decode_String(deserializer);
        return BridgeError_Storage(var_field0);
      case 5:
        var var_field0 = sse_decode_String(deserializer);
        return BridgeError_Capture(var_field0);
      case 6:
        var var_field0 = sse_decode_String(deserializer);
        return BridgeError_Qr(var_field0);
      default:
        throw UnimplementedError('');
    }
  }

  @protected
  BridgeInfo sse_decode_bridge_info(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_coreVersion = sse_decode_String(deserializer);
    var var_dataDir = sse_decode_String(deserializer);
    var var_passportHost = sse_decode_String(deserializer);
    var var_deviceApiHost = sse_decode_String(deserializer);
    var var_games = sse_decode_list_String(deserializer);
    var var_deviceTemplates = sse_decode_list_String(deserializer);
    return BridgeInfo(
      coreVersion: var_coreVersion,
      dataDir: var_dataDir,
      passportHost: var_passportHost,
      deviceApiHost: var_deviceApiHost,
      games: var_games,
      deviceTemplates: var_deviceTemplates,
    );
  }

  @protected
  DeviceSummary sse_decode_device_summary(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_account = sse_decode_String(deserializer);
    var var_model = sse_decode_String(deserializer);
    var var_brand = sse_decode_String(deserializer);
    var var_androidVersion = sse_decode_String(deserializer);
    var var_sdkVersion = sse_decode_String(deserializer);
    var var_gameBiz = sse_decode_String(deserializer);
    var var_deviceIdMasked = sse_decode_String(deserializer);
    var var_deviceIdLen = sse_decode_usize(deserializer);
    var var_deviceFpMasked = sse_decode_String(deserializer);
    var var_deviceFpLen = sse_decode_usize(deserializer);
    var var_registered = sse_decode_bool(deserializer);
    return DeviceSummary(
      account: var_account,
      model: var_model,
      brand: var_brand,
      androidVersion: var_androidVersion,
      sdkVersion: var_sdkVersion,
      gameBiz: var_gameBiz,
      deviceIdMasked: var_deviceIdMasked,
      deviceIdLen: var_deviceIdLen,
      deviceFpMasked: var_deviceFpMasked,
      deviceFpLen: var_deviceFpLen,
      registered: var_registered,
    );
  }

  @protected
  double sse_decode_f_64(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getFloat64();
  }

  @protected
  FlagDto sse_decode_flag_dto(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_enabled = sse_decode_bool(deserializer);
    var var_updatedAt = sse_decode_String(deserializer);
    return FlagDto(enabled: var_enabled, updatedAt: var_updatedAt);
  }

  @protected
  PlatformInt64 sse_decode_i_64(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getPlatformInt64();
  }

  @protected
  List<String> sse_decode_list_String(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <String>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_String(deserializer));
    }
    return ans_;
  }

  @protected
  List<AuditEntryDto> sse_decode_list_audit_entry_dto(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <AuditEntryDto>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_audit_entry_dto(deserializer));
    }
    return ans_;
  }

  @protected
  List<DeviceSummary> sse_decode_list_device_summary(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <DeviceSummary>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_device_summary(deserializer));
    }
    return ans_;
  }

  @protected
  Uint8List sse_decode_list_prim_u_8_strict(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var len_ = sse_decode_i_32(deserializer);
    return deserializer.buffer.getUint8List(len_);
  }

  @protected
  List<StepReport> sse_decode_list_step_report(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <StepReport>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_step_report(deserializer));
    }
    return ans_;
  }

  @protected
  List<WatcherSpecDto> sse_decode_list_watcher_spec_dto(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <WatcherSpecDto>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_watcher_spec_dto(deserializer));
    }
    return ans_;
  }

  @protected
  List<WatcherStateDto> sse_decode_list_watcher_state_dto(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <WatcherStateDto>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_watcher_state_dto(deserializer));
    }
    return ans_;
  }

  @protected
  LoginChallengeDto sse_decode_login_challenge_dto(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_kind = sse_decode_String(deserializer);
    var var_retcode = sse_decode_i_64(deserializer);
    var var_message = sse_decode_String(deserializer);
    var var_hints = sse_decode_list_String(deserializer);
    var var_aigisUrl = sse_decode_opt_String(deserializer);
    var var_aigisHandle = sse_decode_opt_box_autoadd_u_64(deserializer);
    var var_instructions = sse_decode_String(deserializer);
    return LoginChallengeDto(
      kind: var_kind,
      retcode: var_retcode,
      message: var_message,
      hints: var_hints,
      aigisUrl: var_aigisUrl,
      aigisHandle: var_aigisHandle,
      instructions: var_instructions,
    );
  }

  @protected
  String? sse_decode_opt_String(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    if (sse_decode_bool(deserializer)) {
      return (sse_decode_String(deserializer));
    } else {
      return null;
    }
  }

  @protected
  PlatformInt64? sse_decode_opt_box_autoadd_i_64(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    if (sse_decode_bool(deserializer)) {
      return (sse_decode_box_autoadd_i_64(deserializer));
    } else {
      return null;
    }
  }

  @protected
  BigInt? sse_decode_opt_box_autoadd_u_64(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    if (sse_decode_bool(deserializer)) {
      return (sse_decode_box_autoadd_u_64(deserializer));
    } else {
      return null;
    }
  }

  @protected
  QrSource sse_decode_qr_source(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var tag_ = sse_decode_i_32(deserializer);
    switch (tag_) {
      case 0:
        var var_field0 = sse_decode_String(deserializer);
        return QrSource_Url(var_field0);
      case 1:
        var var_field0 = sse_decode_String(deserializer);
        return QrSource_Image(var_field0);
      case 2:
        var var_waitSecs = sse_decode_opt_box_autoadd_u_64(deserializer);
        return QrSource_Screen(waitSecs: var_waitSecs);
      case 3:
        var var_roomId = sse_decode_String(deserializer);
        var var_waitSecs = sse_decode_opt_box_autoadd_u_64(deserializer);
        return QrSource_Bilibili(roomId: var_roomId, waitSecs: var_waitSecs);
      default:
        throw UnimplementedError('');
    }
  }

  @protected
  RaceStatusDto sse_decode_race_status_dto(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_running = sse_decode_bool(deserializer);
    var var_watchersTotal = sse_decode_u_32(deserializer);
    var var_watchersAlive = sse_decode_u_32(deserializer);
    var var_approved = sse_decode_bool(deserializer);
    var var_error = sse_decode_opt_String(deserializer);
    var var_watchers = sse_decode_list_watcher_state_dto(deserializer);
    return RaceStatusDto(
      running: var_running,
      watchersTotal: var_watchersTotal,
      watchersAlive: var_watchersAlive,
      approved: var_approved,
      error: var_error,
      watchers: var_watchers,
    );
  }

  @protected
  RegistrationSummary sse_decode_registration_summary(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_account = sse_decode_String(deserializer);
    var var_deviceIdMasked = sse_decode_String(deserializer);
    var var_deviceFpMasked = sse_decode_String(deserializer);
    var var_deviceFpLen = sse_decode_usize(deserializer);
    return RegistrationSummary(
      account: var_account,
      deviceIdMasked: var_deviceIdMasked,
      deviceFpMasked: var_deviceFpMasked,
      deviceFpLen: var_deviceFpLen,
    );
  }

  @protected
  ScanProgressDto sse_decode_scan_progress_dto(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_frames = sse_decode_u_64(deserializer);
    var var_decoded = sse_decode_u_64(deserializer);
    var var_waitingStable = sse_decode_bool(deserializer);
    var var_lastError = sse_decode_String(deserializer);
    return ScanProgressDto(
      frames: var_frames,
      decoded: var_decoded,
      waitingStable: var_waitingStable,
      lastError: var_lastError,
    );
  }

  @protected
  SessionProbeDto sse_decode_session_probe_dto(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_valid = sse_decode_bool(deserializer);
    var var_message = sse_decode_String(deserializer);
    var var_uidMasked = sse_decode_String(deserializer);
    return SessionProbeDto(
      valid: var_valid,
      message: var_message,
      uidMasked: var_uidMasked,
    );
  }

  @protected
  SessionSummary sse_decode_session_summary(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_account = sse_decode_String(deserializer);
    var var_accountUidLen = sse_decode_usize(deserializer);
    var var_stokenLen = sse_decode_usize(deserializer);
    var var_stokenPrefix = sse_decode_String(deserializer);
    var var_midMasked = sse_decode_String(deserializer);
    var var_qrMidMasked = sse_decode_String(deserializer);
    var var_cookieTokenLen = sse_decode_usize(deserializer);
    var var_ltokenLen = sse_decode_usize(deserializer);
    var var_updatedAt = sse_decode_String(deserializer);
    var var_steps = sse_decode_list_step_report(deserializer);
    return SessionSummary(
      account: var_account,
      accountUidLen: var_accountUidLen,
      stokenLen: var_stokenLen,
      stokenPrefix: var_stokenPrefix,
      midMasked: var_midMasked,
      qrMidMasked: var_qrMidMasked,
      cookieTokenLen: var_cookieTokenLen,
      ltokenLen: var_ltokenLen,
      updatedAt: var_updatedAt,
      steps: var_steps,
    );
  }

  @protected
  SmsRequestDto sse_decode_sms_request_dto(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_sentNew = sse_decode_bool(deserializer);
    var var_countdown = sse_decode_u_64(deserializer);
    var var_actionType = sse_decode_String(deserializer);
    return SmsRequestDto(
      sentNew: var_sentNew,
      countdown: var_countdown,
      actionType: var_actionType,
    );
  }

  @protected
  StepReport sse_decode_step_report(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_index = sse_decode_u_32(deserializer);
    var var_total = sse_decode_u_32(deserializer);
    var var_name = sse_decode_String(deserializer);
    var var_detail = sse_decode_String(deserializer);
    var var_ok = sse_decode_bool(deserializer);
    return StepReport(
      index: var_index,
      total: var_total,
      name: var_name,
      detail: var_detail,
      ok: var_ok,
    );
  }

  @protected
  TextDto sse_decode_text_dto(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_value = sse_decode_String(deserializer);
    return TextDto(value: var_value);
  }

  @protected
  int sse_decode_u_32(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint32();
  }

  @protected
  BigInt sse_decode_u_64(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getBigUint64();
  }

  @protected
  int sse_decode_u_8(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint8();
  }

  @protected
  void sse_decode_unit(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
  }

  @protected
  BigInt sse_decode_usize(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getBigUint64();
  }

  @protected
  WatcherSpecDto sse_decode_watcher_spec_dto(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_kind = sse_decode_String(deserializer);
    var var_room = sse_decode_opt_String(deserializer);
    var var_label = sse_decode_String(deserializer);
    var var_mode = sse_decode_String(deserializer);
    return WatcherSpecDto(
      kind: var_kind,
      room: var_room,
      label: var_label,
      mode: var_mode,
    );
  }

  @protected
  WatcherStateDto sse_decode_watcher_state_dto(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_key = sse_decode_String(deserializer);
    var var_kind = sse_decode_String(deserializer);
    var var_room = sse_decode_opt_String(deserializer);
    var var_label = sse_decode_String(deserializer);
    var var_mode = sse_decode_String(deserializer);
    var var_alive = sse_decode_bool(deserializer);
    var var_winner = sse_decode_bool(deserializer);
    var var_scanned = sse_decode_bool(deserializer);
    var var_approved = sse_decode_bool(deserializer);
    var var_qrUrl = sse_decode_opt_String(deserializer);
    var var_pendingTicket = sse_decode_opt_String(deserializer);
    var var_pendingTokenTypes = sse_decode_list_String(deserializer);
    var var_error = sse_decode_opt_String(deserializer);
    var var_appName = sse_decode_String(deserializer);
    var var_accountDispName = sse_decode_String(deserializer);
    var var_riskNote = sse_decode_String(deserializer);
    var var_frames = sse_decode_u_64(deserializer);
    var var_decodedFrames = sse_decode_u_64(deserializer);
    var var_hint = sse_decode_String(deserializer);
    var var_resolution = sse_decode_String(deserializer);
    var var_fps = sse_decode_f_64(deserializer);
    var var_pingMs = sse_decode_opt_box_autoadd_u_64(deserializer);
    return WatcherStateDto(
      key: var_key,
      kind: var_kind,
      room: var_room,
      label: var_label,
      mode: var_mode,
      alive: var_alive,
      winner: var_winner,
      scanned: var_scanned,
      approved: var_approved,
      qrUrl: var_qrUrl,
      pendingTicket: var_pendingTicket,
      pendingTokenTypes: var_pendingTokenTypes,
      error: var_error,
      appName: var_appName,
      accountDispName: var_accountDispName,
      riskNote: var_riskNote,
      frames: var_frames,
      decodedFrames: var_decodedFrames,
      hint: var_hint,
      resolution: var_resolution,
      fps: var_fps,
      pingMs: var_pingMs,
    );
  }

  @protected
  int sse_decode_i_32(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getInt32();
  }

  @protected
  void
  sse_encode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerCore(
    Core self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_usize(
      (self as CoreImpl).frbInternalSseEncode(move: true),
      serializer,
    );
  }

  @protected
  void
  sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerCore(
    Core self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_usize(
      (self as CoreImpl).frbInternalSseEncode(move: false),
      serializer,
    );
  }

  @protected
  void
  sse_encode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerCore(
    Core self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_usize(
      (self as CoreImpl).frbInternalSseEncode(move: null),
      serializer,
    );
  }

  @protected
  void sse_encode_String(String self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_list_prim_u_8_strict(utf8.encoder.convert(self), serializer);
  }

  @protected
  void sse_encode_aigis_token_dto(
    AigisTokenDto self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.token, serializer);
  }

  @protected
  void sse_encode_approval_outcome(
    ApprovalOutcome self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_list_step_report(self.steps, serializer);
    sse_encode_String(self.appName, serializer);
    sse_encode_String(self.accountDispName, serializer);
    sse_encode_String(self.riskNote, serializer);
    sse_encode_bool(self.scanned, serializer);
    sse_encode_bool(self.approved, serializer);
    sse_encode_String(self.source, serializer);
    sse_encode_opt_String(self.pendingTicket, serializer);
    sse_encode_list_String(self.pendingTokenTypes, serializer);
  }

  @protected
  void sse_encode_audit_entry_dto(
    AuditEntryDto self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.at, serializer);
    sse_encode_String(self.account, serializer);
    sse_encode_String(self.action, serializer);
    sse_encode_bool(self.ok, serializer);
    sse_encode_String(self.detail, serializer);
    sse_encode_opt_box_autoadd_i_64(self.retcode, serializer);
  }

  @protected
  void sse_encode_bool(bool self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint8(self ? 1 : 0);
  }

  @protected
  void sse_encode_box_autoadd_i_64(
    PlatformInt64 self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_64(self, serializer);
  }

  @protected
  void sse_encode_box_autoadd_login_challenge_dto(
    LoginChallengeDto self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_login_challenge_dto(self, serializer);
  }

  @protected
  void sse_encode_box_autoadd_qr_source(
    QrSource self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_qr_source(self, serializer);
  }

  @protected
  void sse_encode_box_autoadd_u_64(BigInt self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_u_64(self, serializer);
  }

  @protected
  void sse_encode_bridge_error(BridgeError self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    switch (self) {
      case BridgeError_Invalid(field0: final field0):
        sse_encode_i_32(0, serializer);
        sse_encode_String(field0, serializer);
      case BridgeError_AccountNotFound(field0: final field0):
        sse_encode_i_32(1, serializer);
        sse_encode_String(field0, serializer);
      case BridgeError_Api(retcode: final retcode, message: final message):
        sse_encode_i_32(2, serializer);
        sse_encode_i_64(retcode, serializer);
        sse_encode_String(message, serializer);
      case BridgeError_Challenge(field0: final field0):
        sse_encode_i_32(3, serializer);
        sse_encode_box_autoadd_login_challenge_dto(field0, serializer);
      case BridgeError_Storage(field0: final field0):
        sse_encode_i_32(4, serializer);
        sse_encode_String(field0, serializer);
      case BridgeError_Capture(field0: final field0):
        sse_encode_i_32(5, serializer);
        sse_encode_String(field0, serializer);
      case BridgeError_Qr(field0: final field0):
        sse_encode_i_32(6, serializer);
        sse_encode_String(field0, serializer);
    }
  }

  @protected
  void sse_encode_bridge_info(BridgeInfo self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.coreVersion, serializer);
    sse_encode_String(self.dataDir, serializer);
    sse_encode_String(self.passportHost, serializer);
    sse_encode_String(self.deviceApiHost, serializer);
    sse_encode_list_String(self.games, serializer);
    sse_encode_list_String(self.deviceTemplates, serializer);
  }

  @protected
  void sse_encode_device_summary(DeviceSummary self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.account, serializer);
    sse_encode_String(self.model, serializer);
    sse_encode_String(self.brand, serializer);
    sse_encode_String(self.androidVersion, serializer);
    sse_encode_String(self.sdkVersion, serializer);
    sse_encode_String(self.gameBiz, serializer);
    sse_encode_String(self.deviceIdMasked, serializer);
    sse_encode_usize(self.deviceIdLen, serializer);
    sse_encode_String(self.deviceFpMasked, serializer);
    sse_encode_usize(self.deviceFpLen, serializer);
    sse_encode_bool(self.registered, serializer);
  }

  @protected
  void sse_encode_f_64(double self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putFloat64(self);
  }

  @protected
  void sse_encode_flag_dto(FlagDto self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_bool(self.enabled, serializer);
    sse_encode_String(self.updatedAt, serializer);
  }

  @protected
  void sse_encode_i_64(PlatformInt64 self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putPlatformInt64(self);
  }

  @protected
  void sse_encode_list_String(List<String> self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_String(item, serializer);
    }
  }

  @protected
  void sse_encode_list_audit_entry_dto(
    List<AuditEntryDto> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_audit_entry_dto(item, serializer);
    }
  }

  @protected
  void sse_encode_list_device_summary(
    List<DeviceSummary> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_device_summary(item, serializer);
    }
  }

  @protected
  void sse_encode_list_prim_u_8_strict(
    Uint8List self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    serializer.buffer.putUint8List(self);
  }

  @protected
  void sse_encode_list_step_report(
    List<StepReport> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_step_report(item, serializer);
    }
  }

  @protected
  void sse_encode_list_watcher_spec_dto(
    List<WatcherSpecDto> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_watcher_spec_dto(item, serializer);
    }
  }

  @protected
  void sse_encode_list_watcher_state_dto(
    List<WatcherStateDto> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_watcher_state_dto(item, serializer);
    }
  }

  @protected
  void sse_encode_login_challenge_dto(
    LoginChallengeDto self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.kind, serializer);
    sse_encode_i_64(self.retcode, serializer);
    sse_encode_String(self.message, serializer);
    sse_encode_list_String(self.hints, serializer);
    sse_encode_opt_String(self.aigisUrl, serializer);
    sse_encode_opt_box_autoadd_u_64(self.aigisHandle, serializer);
    sse_encode_String(self.instructions, serializer);
  }

  @protected
  void sse_encode_opt_String(String? self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    sse_encode_bool(self != null, serializer);
    if (self != null) {
      sse_encode_String(self, serializer);
    }
  }

  @protected
  void sse_encode_opt_box_autoadd_i_64(
    PlatformInt64? self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    sse_encode_bool(self != null, serializer);
    if (self != null) {
      sse_encode_box_autoadd_i_64(self, serializer);
    }
  }

  @protected
  void sse_encode_opt_box_autoadd_u_64(BigInt? self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    sse_encode_bool(self != null, serializer);
    if (self != null) {
      sse_encode_box_autoadd_u_64(self, serializer);
    }
  }

  @protected
  void sse_encode_qr_source(QrSource self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    switch (self) {
      case QrSource_Url(field0: final field0):
        sse_encode_i_32(0, serializer);
        sse_encode_String(field0, serializer);
      case QrSource_Image(field0: final field0):
        sse_encode_i_32(1, serializer);
        sse_encode_String(field0, serializer);
      case QrSource_Screen(waitSecs: final waitSecs):
        sse_encode_i_32(2, serializer);
        sse_encode_opt_box_autoadd_u_64(waitSecs, serializer);
      case QrSource_Bilibili(roomId: final roomId, waitSecs: final waitSecs):
        sse_encode_i_32(3, serializer);
        sse_encode_String(roomId, serializer);
        sse_encode_opt_box_autoadd_u_64(waitSecs, serializer);
    }
  }

  @protected
  void sse_encode_race_status_dto(
    RaceStatusDto self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_bool(self.running, serializer);
    sse_encode_u_32(self.watchersTotal, serializer);
    sse_encode_u_32(self.watchersAlive, serializer);
    sse_encode_bool(self.approved, serializer);
    sse_encode_opt_String(self.error, serializer);
    sse_encode_list_watcher_state_dto(self.watchers, serializer);
  }

  @protected
  void sse_encode_registration_summary(
    RegistrationSummary self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.account, serializer);
    sse_encode_String(self.deviceIdMasked, serializer);
    sse_encode_String(self.deviceFpMasked, serializer);
    sse_encode_usize(self.deviceFpLen, serializer);
  }

  @protected
  void sse_encode_scan_progress_dto(
    ScanProgressDto self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_u_64(self.frames, serializer);
    sse_encode_u_64(self.decoded, serializer);
    sse_encode_bool(self.waitingStable, serializer);
    sse_encode_String(self.lastError, serializer);
  }

  @protected
  void sse_encode_session_probe_dto(
    SessionProbeDto self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_bool(self.valid, serializer);
    sse_encode_String(self.message, serializer);
    sse_encode_String(self.uidMasked, serializer);
  }

  @protected
  void sse_encode_session_summary(
    SessionSummary self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.account, serializer);
    sse_encode_usize(self.accountUidLen, serializer);
    sse_encode_usize(self.stokenLen, serializer);
    sse_encode_String(self.stokenPrefix, serializer);
    sse_encode_String(self.midMasked, serializer);
    sse_encode_String(self.qrMidMasked, serializer);
    sse_encode_usize(self.cookieTokenLen, serializer);
    sse_encode_usize(self.ltokenLen, serializer);
    sse_encode_String(self.updatedAt, serializer);
    sse_encode_list_step_report(self.steps, serializer);
  }

  @protected
  void sse_encode_sms_request_dto(
    SmsRequestDto self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_bool(self.sentNew, serializer);
    sse_encode_u_64(self.countdown, serializer);
    sse_encode_String(self.actionType, serializer);
  }

  @protected
  void sse_encode_step_report(StepReport self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_u_32(self.index, serializer);
    sse_encode_u_32(self.total, serializer);
    sse_encode_String(self.name, serializer);
    sse_encode_String(self.detail, serializer);
    sse_encode_bool(self.ok, serializer);
  }

  @protected
  void sse_encode_text_dto(TextDto self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.value, serializer);
  }

  @protected
  void sse_encode_u_32(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint32(self);
  }

  @protected
  void sse_encode_u_64(BigInt self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putBigUint64(self);
  }

  @protected
  void sse_encode_u_8(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint8(self);
  }

  @protected
  void sse_encode_unit(void self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
  }

  @protected
  void sse_encode_usize(BigInt self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putBigUint64(self);
  }

  @protected
  void sse_encode_watcher_spec_dto(
    WatcherSpecDto self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.kind, serializer);
    sse_encode_opt_String(self.room, serializer);
    sse_encode_String(self.label, serializer);
    sse_encode_String(self.mode, serializer);
  }

  @protected
  void sse_encode_watcher_state_dto(
    WatcherStateDto self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.key, serializer);
    sse_encode_String(self.kind, serializer);
    sse_encode_opt_String(self.room, serializer);
    sse_encode_String(self.label, serializer);
    sse_encode_String(self.mode, serializer);
    sse_encode_bool(self.alive, serializer);
    sse_encode_bool(self.winner, serializer);
    sse_encode_bool(self.scanned, serializer);
    sse_encode_bool(self.approved, serializer);
    sse_encode_opt_String(self.qrUrl, serializer);
    sse_encode_opt_String(self.pendingTicket, serializer);
    sse_encode_list_String(self.pendingTokenTypes, serializer);
    sse_encode_opt_String(self.error, serializer);
    sse_encode_String(self.appName, serializer);
    sse_encode_String(self.accountDispName, serializer);
    sse_encode_String(self.riskNote, serializer);
    sse_encode_u_64(self.frames, serializer);
    sse_encode_u_64(self.decodedFrames, serializer);
    sse_encode_String(self.hint, serializer);
    sse_encode_String(self.resolution, serializer);
    sse_encode_f_64(self.fps, serializer);
    sse_encode_opt_box_autoadd_u_64(self.pingMs, serializer);
  }

  @protected
  void sse_encode_i_32(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putInt32(self);
  }
}

@sealed
class CoreImpl extends RustOpaque implements Core {
  // Not to be used by end users
  CoreImpl.frbInternalDcoDecode(List<dynamic> wire)
    : super.frbInternalDcoDecode(wire, _kStaticData);

  // Not to be used by end users
  CoreImpl.frbInternalSseDecode(BigInt ptr, int externalSizeOnNative)
    : super.frbInternalSseDecode(ptr, externalSizeOnNative, _kStaticData);

  static final _kStaticData = RustArcStaticData(
    rustArcIncrementStrongCount:
        RustLib.instance.api.rust_arc_increment_strong_count_Core,
    rustArcDecrementStrongCount:
        RustLib.instance.api.rust_arc_decrement_strong_count_Core,
    rustArcDecrementStrongCountPtr:
        RustLib.instance.api.rust_arc_decrement_strong_count_CorePtr,
  );

  /// Describe the core to the UI (about/settings screen).
  Future<BridgeInfo> info() =>
      RustLib.instance.api.crateApiCoreCoreInfo(that: this);
}
