// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.13.0.

// ignore_for_file: unused_import, unused_element, unnecessary_import, duplicate_ignore, invalid_use_of_internal_member, annotate_overrides, non_constant_identifier_names, curly_braces_in_flow_control_structures, prefer_const_literals_to_create_immutables, unused_field

import 'api/auth.dart';
import 'api/core.dart';
import 'api/device.dart';
import 'api/qr.dart';
import 'api/race.dart';
import 'api/settings.dart';

import 'dart:async';
import 'dart:convert';
import 'dart:ffi' as ffi;

import 'dto.dart';
import 'error.dart';
import 'frb_generated.dart';

import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated_io.dart';

abstract class RustLibApiImplPlatform extends BaseApiImpl<RustLibWire> {
  RustLibApiImplPlatform({
    required super.handler,
    required super.wire,
    required super.generalizedFrbRustBinding,
    required super.portManager,
  });

  CrossPlatformFinalizerArg get rust_arc_decrement_strong_count_CorePtr => wire
      ._rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerCorePtr;

  @protected
  Core
  dco_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerCore(
    dynamic raw,
  );

  @protected
  Core
  dco_decode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerCore(
    dynamic raw,
  );

  @protected
  Core
  dco_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerCore(
    dynamic raw,
  );

  @protected
  String dco_decode_String(dynamic raw);

  @protected
  AigisTokenDto dco_decode_aigis_token_dto(dynamic raw);

  @protected
  ApprovalOutcome dco_decode_approval_outcome(dynamic raw);

  @protected
  AuditEntryDto dco_decode_audit_entry_dto(dynamic raw);

  @protected
  bool dco_decode_bool(dynamic raw);

  @protected
  PlatformInt64 dco_decode_box_autoadd_i_64(dynamic raw);

  @protected
  LoginChallengeDto dco_decode_box_autoadd_login_challenge_dto(dynamic raw);

  @protected
  QrSource dco_decode_box_autoadd_qr_source(dynamic raw);

  @protected
  BigInt dco_decode_box_autoadd_u_64(dynamic raw);

  @protected
  BridgeError dco_decode_bridge_error(dynamic raw);

  @protected
  BridgeInfo dco_decode_bridge_info(dynamic raw);

  @protected
  DeviceSummary dco_decode_device_summary(dynamic raw);

  @protected
  double dco_decode_f_64(dynamic raw);

  @protected
  FlagDto dco_decode_flag_dto(dynamic raw);

  @protected
  PlatformInt64 dco_decode_i_64(dynamic raw);

  @protected
  List<String> dco_decode_list_String(dynamic raw);

  @protected
  List<AuditEntryDto> dco_decode_list_audit_entry_dto(dynamic raw);

  @protected
  List<DeviceSummary> dco_decode_list_device_summary(dynamic raw);

  @protected
  Uint8List dco_decode_list_prim_u_8_strict(dynamic raw);

  @protected
  List<StepReport> dco_decode_list_step_report(dynamic raw);

  @protected
  List<WatcherSpecDto> dco_decode_list_watcher_spec_dto(dynamic raw);

  @protected
  List<WatcherStateDto> dco_decode_list_watcher_state_dto(dynamic raw);

  @protected
  LoginChallengeDto dco_decode_login_challenge_dto(dynamic raw);

  @protected
  String? dco_decode_opt_String(dynamic raw);

  @protected
  PlatformInt64? dco_decode_opt_box_autoadd_i_64(dynamic raw);

  @protected
  BigInt? dco_decode_opt_box_autoadd_u_64(dynamic raw);

  @protected
  QrSource dco_decode_qr_source(dynamic raw);

  @protected
  RaceStatusDto dco_decode_race_status_dto(dynamic raw);

  @protected
  RegistrationSummary dco_decode_registration_summary(dynamic raw);

  @protected
  ScanProgressDto dco_decode_scan_progress_dto(dynamic raw);

  @protected
  SessionProbeDto dco_decode_session_probe_dto(dynamic raw);

  @protected
  SessionSummary dco_decode_session_summary(dynamic raw);

  @protected
  SmsRequestDto dco_decode_sms_request_dto(dynamic raw);

  @protected
  StepReport dco_decode_step_report(dynamic raw);

  @protected
  TextDto dco_decode_text_dto(dynamic raw);

  @protected
  int dco_decode_u_32(dynamic raw);

  @protected
  BigInt dco_decode_u_64(dynamic raw);

  @protected
  int dco_decode_u_8(dynamic raw);

  @protected
  void dco_decode_unit(dynamic raw);

  @protected
  BigInt dco_decode_usize(dynamic raw);

  @protected
  WatcherSpecDto dco_decode_watcher_spec_dto(dynamic raw);

  @protected
  WatcherStateDto dco_decode_watcher_state_dto(dynamic raw);

  @protected
  Core
  sse_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerCore(
    SseDeserializer deserializer,
  );

  @protected
  Core
  sse_decode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerCore(
    SseDeserializer deserializer,
  );

  @protected
  Core
  sse_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerCore(
    SseDeserializer deserializer,
  );

  @protected
  String sse_decode_String(SseDeserializer deserializer);

  @protected
  AigisTokenDto sse_decode_aigis_token_dto(SseDeserializer deserializer);

  @protected
  ApprovalOutcome sse_decode_approval_outcome(SseDeserializer deserializer);

  @protected
  AuditEntryDto sse_decode_audit_entry_dto(SseDeserializer deserializer);

  @protected
  bool sse_decode_bool(SseDeserializer deserializer);

  @protected
  PlatformInt64 sse_decode_box_autoadd_i_64(SseDeserializer deserializer);

  @protected
  LoginChallengeDto sse_decode_box_autoadd_login_challenge_dto(
    SseDeserializer deserializer,
  );

  @protected
  QrSource sse_decode_box_autoadd_qr_source(SseDeserializer deserializer);

  @protected
  BigInt sse_decode_box_autoadd_u_64(SseDeserializer deserializer);

  @protected
  BridgeError sse_decode_bridge_error(SseDeserializer deserializer);

  @protected
  BridgeInfo sse_decode_bridge_info(SseDeserializer deserializer);

  @protected
  DeviceSummary sse_decode_device_summary(SseDeserializer deserializer);

  @protected
  double sse_decode_f_64(SseDeserializer deserializer);

  @protected
  FlagDto sse_decode_flag_dto(SseDeserializer deserializer);

  @protected
  PlatformInt64 sse_decode_i_64(SseDeserializer deserializer);

  @protected
  List<String> sse_decode_list_String(SseDeserializer deserializer);

  @protected
  List<AuditEntryDto> sse_decode_list_audit_entry_dto(
    SseDeserializer deserializer,
  );

  @protected
  List<DeviceSummary> sse_decode_list_device_summary(
    SseDeserializer deserializer,
  );

  @protected
  Uint8List sse_decode_list_prim_u_8_strict(SseDeserializer deserializer);

  @protected
  List<StepReport> sse_decode_list_step_report(SseDeserializer deserializer);

  @protected
  List<WatcherSpecDto> sse_decode_list_watcher_spec_dto(
    SseDeserializer deserializer,
  );

  @protected
  List<WatcherStateDto> sse_decode_list_watcher_state_dto(
    SseDeserializer deserializer,
  );

  @protected
  LoginChallengeDto sse_decode_login_challenge_dto(
    SseDeserializer deserializer,
  );

  @protected
  String? sse_decode_opt_String(SseDeserializer deserializer);

  @protected
  PlatformInt64? sse_decode_opt_box_autoadd_i_64(SseDeserializer deserializer);

  @protected
  BigInt? sse_decode_opt_box_autoadd_u_64(SseDeserializer deserializer);

  @protected
  QrSource sse_decode_qr_source(SseDeserializer deserializer);

  @protected
  RaceStatusDto sse_decode_race_status_dto(SseDeserializer deserializer);

  @protected
  RegistrationSummary sse_decode_registration_summary(
    SseDeserializer deserializer,
  );

  @protected
  ScanProgressDto sse_decode_scan_progress_dto(SseDeserializer deserializer);

  @protected
  SessionProbeDto sse_decode_session_probe_dto(SseDeserializer deserializer);

  @protected
  SessionSummary sse_decode_session_summary(SseDeserializer deserializer);

  @protected
  SmsRequestDto sse_decode_sms_request_dto(SseDeserializer deserializer);

  @protected
  StepReport sse_decode_step_report(SseDeserializer deserializer);

  @protected
  TextDto sse_decode_text_dto(SseDeserializer deserializer);

  @protected
  int sse_decode_u_32(SseDeserializer deserializer);

  @protected
  BigInt sse_decode_u_64(SseDeserializer deserializer);

  @protected
  int sse_decode_u_8(SseDeserializer deserializer);

  @protected
  void sse_decode_unit(SseDeserializer deserializer);

  @protected
  BigInt sse_decode_usize(SseDeserializer deserializer);

  @protected
  WatcherSpecDto sse_decode_watcher_spec_dto(SseDeserializer deserializer);

  @protected
  WatcherStateDto sse_decode_watcher_state_dto(SseDeserializer deserializer);

  @protected
  int sse_decode_i_32(SseDeserializer deserializer);

  @protected
  void
  sse_encode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerCore(
    Core self,
    SseSerializer serializer,
  );

  @protected
  void
  sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerCore(
    Core self,
    SseSerializer serializer,
  );

  @protected
  void
  sse_encode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerCore(
    Core self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_String(String self, SseSerializer serializer);

  @protected
  void sse_encode_aigis_token_dto(AigisTokenDto self, SseSerializer serializer);

  @protected
  void sse_encode_approval_outcome(
    ApprovalOutcome self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_audit_entry_dto(AuditEntryDto self, SseSerializer serializer);

  @protected
  void sse_encode_bool(bool self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_i_64(
    PlatformInt64 self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_login_challenge_dto(
    LoginChallengeDto self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_qr_source(
    QrSource self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_u_64(BigInt self, SseSerializer serializer);

  @protected
  void sse_encode_bridge_error(BridgeError self, SseSerializer serializer);

  @protected
  void sse_encode_bridge_info(BridgeInfo self, SseSerializer serializer);

  @protected
  void sse_encode_device_summary(DeviceSummary self, SseSerializer serializer);

  @protected
  void sse_encode_f_64(double self, SseSerializer serializer);

  @protected
  void sse_encode_flag_dto(FlagDto self, SseSerializer serializer);

  @protected
  void sse_encode_i_64(PlatformInt64 self, SseSerializer serializer);

  @protected
  void sse_encode_list_String(List<String> self, SseSerializer serializer);

  @protected
  void sse_encode_list_audit_entry_dto(
    List<AuditEntryDto> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_device_summary(
    List<DeviceSummary> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_prim_u_8_strict(
    Uint8List self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_step_report(
    List<StepReport> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_watcher_spec_dto(
    List<WatcherSpecDto> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_watcher_state_dto(
    List<WatcherStateDto> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_login_challenge_dto(
    LoginChallengeDto self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_opt_String(String? self, SseSerializer serializer);

  @protected
  void sse_encode_opt_box_autoadd_i_64(
    PlatformInt64? self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_opt_box_autoadd_u_64(BigInt? self, SseSerializer serializer);

  @protected
  void sse_encode_qr_source(QrSource self, SseSerializer serializer);

  @protected
  void sse_encode_race_status_dto(RaceStatusDto self, SseSerializer serializer);

  @protected
  void sse_encode_registration_summary(
    RegistrationSummary self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_scan_progress_dto(
    ScanProgressDto self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_session_probe_dto(
    SessionProbeDto self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_session_summary(
    SessionSummary self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_sms_request_dto(SmsRequestDto self, SseSerializer serializer);

  @protected
  void sse_encode_step_report(StepReport self, SseSerializer serializer);

  @protected
  void sse_encode_text_dto(TextDto self, SseSerializer serializer);

  @protected
  void sse_encode_u_32(int self, SseSerializer serializer);

  @protected
  void sse_encode_u_64(BigInt self, SseSerializer serializer);

  @protected
  void sse_encode_u_8(int self, SseSerializer serializer);

  @protected
  void sse_encode_unit(void self, SseSerializer serializer);

  @protected
  void sse_encode_usize(BigInt self, SseSerializer serializer);

  @protected
  void sse_encode_watcher_spec_dto(
    WatcherSpecDto self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_watcher_state_dto(
    WatcherStateDto self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_i_32(int self, SseSerializer serializer);
}

// Section: wire_class

class RustLibWire implements BaseWire {
  factory RustLibWire.fromExternalLibrary(ExternalLibrary lib) =>
      RustLibWire(lib.ffiDynamicLibrary);

  /// Holds the symbol lookup function.
  final ffi.Pointer<T> Function<T extends ffi.NativeType>(String symbolName)
  _lookup;

  /// The symbols are looked up in [dynamicLibrary].
  RustLibWire(ffi.DynamicLibrary dynamicLibrary)
    : _lookup = dynamicLibrary.lookup;

  void
  rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerCore(
    ffi.Pointer<ffi.Void> ptr,
  ) {
    return _rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerCore(
      ptr,
    );
  }

  late final _rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerCorePtr =
      _lookup<ffi.NativeFunction<ffi.Void Function(ffi.Pointer<ffi.Void>)>>(
        'frbgen_mhy_qrscanner_rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerCore',
      );
  late final _rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerCore =
      _rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerCorePtr
          .asFunction<void Function(ffi.Pointer<ffi.Void>)>();

  void
  rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerCore(
    ffi.Pointer<ffi.Void> ptr,
  ) {
    return _rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerCore(
      ptr,
    );
  }

  late final _rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerCorePtr =
      _lookup<ffi.NativeFunction<ffi.Void Function(ffi.Pointer<ffi.Void>)>>(
        'frbgen_mhy_qrscanner_rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerCore',
      );
  late final _rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerCore =
      _rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerCorePtr
          .asFunction<void Function(ffi.Pointer<ffi.Void>)>();
}
