// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.13.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../dto.dart';
import '../error.dart';
import '../frb_generated.dart';
import 'core.dart';

import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `audit`, `begin_aigis_challenge`, `build_headers`, `challenge_error`, `challenge_from_body`, `classify`, `finalize_session`, `login_password`, `new_session`, `request_sms`, `submit_sms`

/// Probe the stored session against the server: does the stoken still work?
/// Used at startup (restore) and before scanning, so an expired login is
/// reported plainly instead of failing mid-race.
Future<SessionProbeDto> sessionProbe({
  required Core core,
  required String account,
}) =>
    RustLib.instance.api.crateApiAuthSessionProbe(core: core, account: account);

/// Password login. `password` is used for this single request and never stored.
Future<SessionSummary> authLoginPassword({
  required Core core,
  required String account,
  required String login,
  required String password,
  String? aigisToken,
}) => RustLib.instance.api.crateApiAuthAuthLoginPassword(
  core: core,
  account: account,
  login: login,
  password: password,
  aigisToken: aigisToken,
);

/// Ask the server to send an SMS verification code. The code is entered by the user.
Future<SmsRequestDto> authRequestSms({
  required Core core,
  required String account,
  required String login,
  required String areaCode,
  String? aigisToken,
}) => RustLib.instance.api.crateApiAuthAuthRequestSms(
  core: core,
  account: account,
  login: login,
  areaCode: areaCode,
  aigisToken: aigisToken,
);

/// Fetch the solved header value from a started aigis session (blocks until
/// the in-app webview posts the result, or the timeout hits).
Future<AigisTokenDto> aigisTake({
  required BigInt handle,
  required BigInt timeoutSecs,
}) => RustLib.instance.api.crateApiAuthAigisTake(
  handle: handle,
  timeoutSecs: timeoutSecs,
);

/// Drop a pending aigis solve (user closed the dialog without solving).
Future<void> aigisCancel({required BigInt handle}) =>
    RustLib.instance.api.crateApiAuthAigisCancel(handle: handle);

/// Complete an SMS login with a user-supplied code.
Future<SessionSummary> authSubmitSms({
  required Core core,
  required String account,
  required String login,
  required String areaCode,
  required String code,
}) => RustLib.instance.api.crateApiAuthAuthSubmitSms(
  core: core,
  account: account,
  login: login,
  areaCode: areaCode,
  code: code,
);

/// Masked view of a stored session.
Future<SessionSummary> authShow({
  required Core core,
  required String account,
}) => RustLib.instance.api.crateApiAuthAuthShow(core: core, account: account);

/// Drop the stored session, keeping the device profile.
Future<void> authLogout({required Core core, required String account}) =>
    RustLib.instance.api.crateApiAuthAuthLogout(core: core, account: account);
