// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.13.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../dto.dart';
import '../frb_generated.dart';

import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `data_dir`, `device_api_host`, `panda_host_for`, `passport_host`, `store`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `clone`, `fmt`
// These functions have error during generation (see debug logs or enable `stop_on_error: true` for more details): `new`, `with_device_api_host`, `with_panda_host`, `with_passport_host`

/// Default per-user data directory (`%LOCALAPPDATA%\mhy\QRscanner`).
Future<String> defaultDataDir() =>
    RustLib.instance.api.crateApiCoreDefaultDataDir();

/// Create the core handle at the default per-user data directory.
Future<Core> coreNew() => RustLib.instance.api.crateApiCoreCoreNew();

/// Create the core handle at an explicit directory (alternate profile, tests).
Future<Core> coreNewAt({required String dataDir}) =>
    RustLib.instance.api.crateApiCoreCoreNewAt(dataDir: dataDir);

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<Core>>
abstract class Core implements RustOpaqueInterface {
  /// Describe the core to the UI (about/settings screen).
  Future<BridgeInfo> info();
}
