// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.13.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../dto.dart';
import '../error.dart';
import '../frb_generated.dart';
import 'core.dart';

import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `ensure_profile`, `parse_template`

/// Create a virtual device profile for an account.
///
/// `force` replaces an existing profile and drops its stale registration.
Future<DeviceSummary> deviceCreate({
  required Core core,
  required String account,
  required String template,
  required bool force,
}) => RustLib.instance.api.crateApiDeviceDeviceCreate(
  core: core,
  account: account,
  template: template,
  force: force,
);

/// Register the stored device with Miyoushe (`getExtList` + `getFp`).
Future<RegistrationSummary> deviceRegister({
  required Core core,
  required String account,
}) => RustLib.instance.api.crateApiDeviceDeviceRegister(
  core: core,
  account: account,
);

/// Read the stored device profile (masked).
Future<DeviceSummary> deviceShow({
  required Core core,
  required String account,
}) =>
    RustLib.instance.api.crateApiDeviceDeviceShow(core: core, account: account);

/// Set the profile's `game_biz` (kept separate from `device_create` so the UI can
/// switch titles without rotating the device identity).
Future<DeviceSummary> deviceSetGameBiz({
  required Core core,
  required String account,
  required String gameBiz,
}) => RustLib.instance.api.crateApiDeviceDeviceSetGameBiz(
  core: core,
  account: account,
  gameBiz: gameBiz,
);

/// Every stored device profile, ordered by label (masked).
///
/// Enumeration walks the `accounts/` directory of the shared data dir, so
/// profiles created by the CLI are visible here too — both entry points open
/// the same store.
Future<List<DeviceSummary>> deviceList({required Core core}) =>
    RustLib.instance.api.crateApiDeviceDeviceList(core: core);

/// Delete one account's device profile, registration, session, and approval
/// policy. The audit log entry stays — history is append-only.
Future<void> deviceDelete({required Core core, required String account}) =>
    RustLib.instance.api.crateApiDeviceDeviceDelete(
      core: core,
      account: account,
    );
