// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.13.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../dto.dart';
import '../error.dart';
import '../frb_generated.dart';
import 'core.dart';

import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';
import 'package:freezed_annotation/freezed_annotation.dart' hide protected;
part 'qr.freezed.dart';

// These functions are ignored because they are not marked as `pub`: `approve_game_url`, `approve_or_skip`, `bilibili_stable_qr`, `build_headers`, `cancel`, `capture_stable_qr`, `load_session`, `login_game`, `note_frame`, `progress_frame`, `progress_reset`, `progress`, `resolve_game_url`, `scan_only`, `scan_passport`, `seen_tickets`, `ticket_is_fresh`, `ticket_mark`, `title_biz`, `watch_bilibili`, `watch_screen`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `assert_fields_are_eq`, `clone`, `eq`, `fmt`

/// UI 的「停止捕获」按钮：让当前进行中的单路扫描在下个帧边界退出。
Future<void> scanStop() => RustLib.instance.api.crateApiQrScanStop();

/// 单路捕获的实时进度。界面每秒轮询一次，把「在扫、扫到什么」显示出来，
/// 避免长时间无反馈让人以为工具没工作。
Future<ScanProgressDto> qrScanProgress() =>
    RustLib.instance.api.crateApiQrQrScanProgress();

/// Approve (or just scan) a game QR in one call.
///
/// `confirm = false` scans only: useful as a dry run and as the first half of a
/// manual-confirmation dialog.
Future<ApprovalOutcome> qrLoginGame({
  required Core core,
  required String account,
  required QrSource source,
  required bool confirm,
}) => RustLib.instance.api.crateApiQrQrLoginGame(
  core: core,
  account: account,
  source: source,
  confirm: confirm,
);

/// Scan an already-decoded passport QR URL (the V2 form).
Future<ApprovalOutcome> qrScan({
  required Core core,
  required String account,
  required String passportQrUrl,
  required bool confirm,
}) => RustLib.instance.api.crateApiQrQrScan(
  core: core,
  account: account,
  passportQrUrl: passportQrUrl,
  confirm: confirm,
);

/// Complete a scan-only run: approve the ticket that 扫描 already fetched.
Future<ApprovalOutcome> qrConfirmPending({
  required Core core,
  required String account,
  required String ticket,
  required List<String> tokenTypes,
}) => RustLib.instance.api.crateApiQrQrConfirmPending(
  core: core,
  account: account,
  ticket: ticket,
  tokenTypes: tokenTypes,
);

/// Cancel a pending approval. Accepts a passport QR URL or a bare ticket.
Future<void> qrCancel({
  required Core core,
  required String account,
  required String urlOrTicket,
  required List<String> tokenTypes,
}) => RustLib.instance.api.crateApiQrQrCancel(
  core: core,
  account: account,
  urlOrTicket: urlOrTicket,
  tokenTypes: tokenTypes,
);

@freezed
sealed class QrSource with _$QrSource {
  const QrSource._();

  /// An already-decoded V1 game QR URL.
  const factory QrSource.url(String field0) = QrSource_Url;

  /// Path to a screenshot containing the QR.
  const factory QrSource.image(String field0) = QrSource_Image;

  /// Capture the screen until a stable QR appears. `wait_secs = None` keeps
  /// scanning with no timeout (the default the UI sends); a value stops with
  /// an error after that many seconds.
  const factory QrSource.screen({BigInt? waitSecs}) = QrSource_Screen;

  /// Pull a Bilibili room's live stream via ffmpeg and decode frames until a
  /// stable QR appears (same wait semantics as `Screen`). The charter input
  /// path: lower latency than capturing a player window.
  const factory QrSource.bilibili({required String roomId, BigInt? waitSecs}) =
      QrSource_Bilibili;
}
