// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.13.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../dto.dart';
import '../error.dart';
import '../frb_generated.dart';
import 'core.dart';

import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `races`, `run_watcher`, `watcher_key`
// These types are ignored because they are neither used by any `pub` functions nor (for structs and enums) marked `#[frb(unignore)]`: `RaceHandle`, `RaceInner`
// These functions are ignored (category: IgnoreBecauseOwnerTyShouldIgnore): `default`

/// Start a race across the given sources. The first stable QR claims the win;
/// mode decides whether the win auto-approves or parks a pending ticket.
Future<int> qrRaceStart({
  required Core core,
  required String account,
  required List<WatcherSpecDto> specs,
  BigInt? waitSecs,
}) => RustLib.instance.api.crateApiRaceQrRaceStart(
  core: core,
  account: account,
  specs: specs,
  waitSecs: waitSecs,
);

/// Snapshot one race's status. Unknown ids read as "not running".
Future<RaceStatusDto> qrRaceStatus({required int id}) =>
    RustLib.instance.api.crateApiRaceQrRaceStatus(id: id);

/// Signal every watcher to stand down; threads detach and finish on their
/// next frame boundary.
Future<void> qrRaceStop({required int id}) =>
    RustLib.instance.api.crateApiRaceQrRaceStop(id: id);

/// 退出前的收尾：停掉所有竞速源与单路扫描。各源线程退出时会 drop 掉
/// FramePump，ffmpeg 子进程随之被 kill——若直接 exit(0)，Rust 析构不会
/// 运行，ffmpeg 会变成孤儿进程继续偷偷拉流。有界等待最多 ~2 秒。
Future<void> appShutdown() => RustLib.instance.api.crateApiRaceAppShutdown();
