// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.13.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../dto.dart';
import '../error.dart';
import '../frb_generated.dart';
import 'core.dart';

import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `policy_key`, `record`, `rotate_if_oversized`, `validate_flag_key`

/// Read one persisted boolean flag. A missing record means `false` — the safe
/// default for every flag we ship.
Future<FlagDto> flagGet({required Core core, required String key}) =>
    RustLib.instance.api.crateApiSettingsFlagGet(core: core, key: key);

Future<FlagDto> flagSet({
  required Core core,
  required String key,
  required bool enabled,
}) => RustLib.instance.api.crateApiSettingsFlagSet(
  core: core,
  key: key,
  enabled: enabled,
);

/// Read one persisted string setting (empty when unset).
Future<TextDto> textGet({required Core core, required String key}) =>
    RustLib.instance.api.crateApiSettingsTextGet(core: core, key: key);

Future<TextDto> textSet({
  required Core core,
  required String key,
  required String value,
}) => RustLib.instance.api.crateApiSettingsTextSet(
  core: core,
  key: key,
  value: value,
);

/// Newest audit entries first, at most `limit` of them.
Future<List<AuditEntryDto>> auditRecent({
  required Core core,
  required int limit,
}) =>
    RustLib.instance.api.crateApiSettingsAuditRecent(core: core, limit: limit);
